const assert=require('node:assert/strict'),path=require('path');let pw;try{pw=require('playwright')}catch{pw=require(path.resolve(path.dirname(process.execPath),'../node_modules/playwright'))}
(async()=>{const b=await pw.chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'}),p=await b.newPage({viewport:{width:1500,height:1050}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(require('url').pathToFileURL(path.resolve('dist/plan_studio.html')).href);
 // Approximate the supplied 12 m² room, with two top windows and a bottom-right door.
 await p.evaluate(()=>{Studio.loadProject({v:'5',n:[{id:'a',x:0,y:0},{id:'b',x:386.5,y:0},{id:'c',x:386.5,y:320},{id:'d',x:0,y:320}],s:[{id:'ab',n1:'a',n2:'b',k:10},{id:'bc',n1:'b',n2:'c',k:10},{id:'cd',n1:'c',n2:'d',k:10},{id:'da',n1:'d',n2:'a',k:10}],e:[{id:'w1',tip_:'pencere',segId:'ab',t:85/386.5,en:80,yuk:125},{id:'w2',tip_:'pencere',segId:'ab',t:320/386.5,en:80,yuk:125},{id:'door',tip_:'kapi',segId:'bc',t:265/320,en:80,yuk:210}],r:[]});G.rooms[0].tip='yatak';draw();});
 const result=await p.evaluate(()=>{const before=Studio.snapshot(),plans=FurnitureLayout.propose(G.rooms[0],{nightstands:'all'}),ctx=FurnitureLayout.context(G.rooms[0]);return {before,unchanged:before===Studio.snapshot(),plans,valid:plans.every(p=>p.fixtures.every((f,i)=>FurnitureLayout.valid(f,p.fixtures.slice(0,i),ctx))&&FurnitureLayout.circulation(ctx,p.fixtures))};});
 console.log('compact room',result.plans.map(p=>({mode:p.nightstandMode,kinds:p.fixtures.map(f=>f.kind),ward:p.fixtures.find(f=>f.kind==='wardrobe')?.w})));
 assert.equal(result.unchanged,true);assert.equal(result.valid,true);assert.ok(result.plans.some(p=>p.nightstandMode==='both'&&p.fixtures.some(f=>f.kind==='wardrobe')));
 assert.ok(result.plans.every(p=>p.fixtures.some(f=>f.kind==='wardrobe')));
 for(const mode of ['both','left','right','none'])assert.ok(result.plans.some(p=>p.nightstandMode===mode),mode);
 await p.evaluate(()=>FurnitureUI.openAuto(G.rooms[0]));await p.selectOption('#furnitureNightstands','both');await p.click('#furnitureGenerate');await p.waitForFunction(()=>!document.getElementById('furnitureApply').disabled);assert.match(await p.textContent('#furnitureResult'),/İki komodin.*Gardırop/);await p.screenshot({path:'artifacts/bedroom-layout-5.9.14.png'});await p.click('#furnitureApply');assert.equal(await p.evaluate(()=>G.fixtures.filter(f=>f.kind==='nightstand').length),2);assert.equal(await p.evaluate(()=>G.fixtures.filter(f=>f.kind==='wardrobe').length),1);await p.evaluate(()=>geriAl());assert.equal(await p.evaluate(()=>G.fixtures.length),0);
 // Keep the existing bed and one bedside table: add only the other table and wardrobe.
 const both=result.plans.find(p=>p.nightstandMode==='both'),kept=both.fixtures.filter(f=>f.kind.startsWith('bed')||f.kind==='nightstand').slice(0,2).map((f,i)=>({...f,id:'kept'+i,locked:true}));
 const fill=await p.evaluate(kept=>{G.fixtures=kept;const before=JSON.stringify(G.fixtures),plans=FurnitureLayout.propose(G.rooms[0],{nightstands:'both'});return {unchanged:JSON.stringify(G.fixtures)===before,plans};},kept);assert.equal(fill.unchanged,true);assert.ok(fill.plans.length);assert.equal(fill.plans[0].fixtures.filter(f=>f.kind.startsWith('bed')).length,0);assert.equal(fill.plans[0].fixtures.filter(f=>f.kind==='nightstand').length,1);assert.equal(fill.plans[0].fixtures.filter(f=>f.kind==='wardrobe').length,1);
 // An impossible wardrobe is reported, never silently marked complete.
 const impossible=await p.evaluate(()=>{G.fixtures=[];const old=FurnitureCatalog.items.wardrobe.sizes;FurnitureCatalog.items.wardrobe.sizes=[[1000,60]];try{return FurnitureLayout.propose(G.rooms[0],{nightstands:'none'}).map(p=>p.missing);}finally{FurnitureCatalog.items.wardrobe.sizes=old;}});assert.ok(impossible.length);assert.ok(impossible.every(m=>m.some(s=>s.includes('Gardırop'))));
 assert.deepEqual(errors,[]);console.log('PASS compact bedroom joint search, both/left/right/none, narrow wardrobe, preview/apply/undo, existing furniture and explicit missing wardrobe');await b.close();})().catch(e=>{console.error(e);process.exit(1)});
