const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{pathToFileURL}=require('url');let pw;try{pw=require('playwright')}catch{pw=require(path.resolve(path.dirname(process.execPath),'../node_modules/playwright'))}
(async()=>{const b=await pw.chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{
 const p=await b.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(pathToFileURL(path.resolve('dist/plan_studio.html')).href);
 await p.evaluate(d=>Studio.loadProject(d),JSON.parse(fs.readFileSync('cizimler/2026-10-02-tuna84-dwg-esleme-taslak.json')));
 const result=await p.evaluate(()=>{const before=JSON.stringify(Studio.state()),a=PlanExport.dxfObjects(),simple=PlanExport.makeDxf('simple'),detail=PlanExport.makeDxf('panels'),noHatch=PlanExport.makeDxf('simple',false),full=PlanExport.makeDxf('current');return {before,after:JSON.stringify(Studio.state()),simple,detail,noHatch,full,dimensions:a.filter(e=>e.dimension).map(e=>({length:Math.hypot(e.p1.x-e.p0.x,e.p1.y-e.p0.y),text:e.txt})),hatch:a.filter(e=>e.hatch).length,wet:G.rooms.filter(r=>['banyo','ebanyo','wc','veranda'].includes(r.tip)).length,corners:a.filter(e=>e.blockName?.startsWith('PS_BAGLANTI_kose')).map(e=>e.items.map(i=>({w:Math.max(...i.points.map(p=>p.x))-Math.min(...i.points.map(p=>p.x)),h:Math.max(...i.points.map(p=>p.y))-Math.min(...i.points.map(p=>p.y))}))),panels:a.filter(e=>e.blockName?.startsWith('PS_PANEL_')).length};});
 assert.equal(result.before,result.after);assert.equal(result.panels,49);assert.equal(result.hatch,result.wet);assert.equal(result.hatch,2);
 assert.ok(result.corners.length>=4);for(const c of result.corners){assert.equal(c.length,1);assert.deepEqual([c[0].w,c[0].h].sort((a,b)=>a-b),[5,10]);}
 for(const d of result.dimensions)assert.ok(Math.abs(d.length-Number(d.text.replace(',','.')))<.011);
 const count=(s,type)=>(s.match(new RegExp('0\\r\\n'+type+'\\r\\n','g'))||[]).length;
 assert.equal(count(result.simple,'HATCH'),2);assert.equal(count(result.noHatch,'HATCH'),0);assert.ok(count(result.simple,'DIMENSION')>0);assert.ok(count(result.detail,'DIMENSION')>count(result.simple,'DIMENSION'));assert.ok(!result.simple.includes('PS_MAKAS_'));assert.ok(result.full.includes('PS_MAKAS_'));assert.ok(!result.simple.includes('PS_OLCU_'));
 fs.mkdirSync('artifacts/export',{recursive:true});fs.writeFileSync('artifacts/export/simple.dxf',result.simple);fs.writeFileSync('artifacts/export/detail.dxf',result.detail);
 await p.locator('#export-dxf').click();assert.equal(await p.locator('#dxfMode').inputValue(),'simple');assert.ok(await p.locator('#dxfHatch').isChecked());await p.screenshot({path:'artifacts/export/cad-dialog.png'});await p.locator('#exportCancel').click();assert.equal(await p.evaluate(()=>JSON.stringify(Studio.state())),result.before);
 const fail=await p.evaluate(()=>{const old=CadSymbols.dimension,s=JSON.stringify(Studio.state());CadSymbols.dimension=()=>{throw Error('injected')};try{PlanExport.makeDxf('simple');}catch{}finally{CadSymbols.dimension=old;}return s===JSON.stringify(Studio.state());});assert.ok(fail);assert.deepEqual(errors,[]);
 console.log('PASS native dimensions, one hatch per wet/veranda room, 49 panel blocks, 10x5 corners, simple/detail/filters, dialog and failure restoration');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
