const assert=require('node:assert/strict'),path=require('path');let pw;try{pw=require('playwright')}catch{pw=require(path.resolve(path.dirname(process.execPath),'../node_modules/playwright'))}
(async()=>{const b=await pw.chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'}),p=await b.newPage({viewport:{width:1600,height:1100}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(require('url').pathToFileURL(path.resolve('dist/plan_studio.html')).href);
 const load=async(w=600,h=500,tip='yatak')=>p.evaluate(({w,h,tip})=>{Studio.loadProject({v:'5',n:[{id:'a',x:0,y:0},{id:'b',x:w,y:0},{id:'c',x:w,y:h},{id:'d',x:0,y:h}],s:[{id:'ab',n1:'a',n2:'b',k:10},{id:'bc',n1:'b',n2:'c',k:10},{id:'cd',n1:'c',n2:'d',k:10},{id:'da',n1:'d',n2:'a',k:10}],e:[{id:'door',segId:'cd',t:.18,tip_:'kapi',en:80,yuk:205},{id:'window',segId:'ab',t:.5,tip_:'pencere',en:120,yuk:120}],r:[]});G.rooms[0].tip=tip;draw();},{w,h,tip});
 await load();await p.click('#t-furniture');assert.equal(await p.locator('[data-furniture]').count(),10);await p.screenshot({path:'artifacts/furniture-catalog-5.9.13.png'});await p.click('[data-furniture="bedDouble"]');assert.equal(await p.inputValue('#fixtureWidth'),'166');assert.equal(await p.inputValue('#fixtureDepth'),'215');await p.fill('#fixtureWidth','180');await p.fill('#fixtureDepth','220');await p.locator('#fixtureDialog button[type=submit]').click();
 const click=async(x,y)=>{const a=await p.evaluate(({x,y})=>{const r=cv.getBoundingClientRect(),p=toCv(x,y);return {x:r.left+p.x,y:r.top+p.y};},{x,y});await p.mouse.click(a.x,a.y);};await click(200,220);assert.equal(await p.evaluate(()=>G.fixtures[0].w),180);
 await p.click('#furnitureLock');const locked=await p.evaluate(()=>({...G.fixtures[0]}));await p.evaluate(()=>Fixtures.rotate());assert.deepEqual(await p.evaluate(()=>G.fixtures[0]),locked);
 const saved=await p.evaluate(()=>Studio.state());await p.evaluate(d=>Studio.loadProject(d),saved);assert.equal(await p.evaluate(()=>G.fixtures[0].locked),true);
 await load();const perf=Date.now();
 const result=await p.evaluate(()=>{const state=Studio.snapshot(),plans=FurnitureLayout.propose(G.rooms[0],{bed:'double'}),ctx=FurnitureLayout.context(G.rooms[0]);return {unchanged:state===Studio.snapshot(),count:plans.length,kinds:plans.map(p=>p.fixtures.map(f=>f.kind)),valid:plans.every(p=>p.fixtures.every((f,i)=>FurnitureLayout.valid(f,p.fixtures.slice(0,i),ctx))&&FurnitureLayout.circulation(ctx,p.fixtures)),missing:plans.map(p=>p.missing)};});console.log('bedroom',Date.now()-perf,result);assert.equal(result.unchanged,true);assert.ok(result.count>0);assert.equal(result.valid,true);assert.ok(result.kinds[0].includes('bedDouble'));
 await p.click('#t-furniture');await p.click('#furnitureAuto');await p.click('#furnitureGenerate');await p.waitForFunction(()=>!document.getElementById('furnitureApply').disabled,{timeout:30000});await p.screenshot({path:'artifacts/furniture-bedroom-preview-5.9.13.png'});assert.equal(await p.evaluate(()=>G.fixtures.length),0);await p.click('#furnitureApply');assert.ok(await p.evaluate(()=>G.fixtures.length)>0);await p.evaluate(()=>geriAl());assert.equal(await p.evaluate(()=>G.fixtures.length),0);await p.evaluate(()=>ileriAl());assert.ok(await p.evaluate(()=>G.fixtures.length)>0);
 for(const tip of ['salon','giris','mutfak','cocuk']){await load(650,550,tip);const result=await p.evaluate(()=>{const a=Date.now(),plans=FurnitureLayout.propose(G.rooms[0],{});return {time:Date.now()-a,count:plans.length,kinds:plans[0]?.fixtures.map(f=>f.kind),missing:plans[0]?.missing};});console.log(tip,result);assert.ok(result.count>0,tip);}
 // Cancel preserves the plan; stale suggestions cannot overwrite subsequent edits.
 await load(650,550,'salon');await p.evaluate(()=>FurnitureUI.openAuto(G.rooms[0]));const pre=await p.evaluate(()=>Studio.snapshot());await p.click('#furnitureGenerate');await p.waitForFunction(()=>!document.getElementById('furnitureApply').disabled);await p.screenshot({path:'artifacts/furniture-living-preview-5.9.13.png'});await p.locator('#furnitureAutoDialog [data-close]').click();assert.equal(await p.evaluate(()=>Studio.snapshot()),pre);
 await p.evaluate(()=>FurnitureUI.openAuto(G.rooms[0]));await p.click('#furnitureGenerate');await p.waitForFunction(()=>!document.getElementById('furnitureApply').disabled);await p.evaluate(()=>Studio.edit(()=>G.fixtures.push({id:'existing',kind:'coatCabinet',w:120,d:40,x:90,y:30,angle:0,mirror:false,locked:true})));await p.click('#furnitureApply');assert.match(await p.textContent('#furnitureResult'),/Plan değişti/);assert.equal(await p.evaluate(()=>G.fixtures.length),1);await p.click('#furnitureGenerate');await p.waitForFunction(()=>!document.getElementById('furnitureApply').disabled);const existing=await p.evaluate(()=>({...G.fixtures[0]}));await p.click('#furnitureApply');assert.deepEqual(await p.evaluate(()=>G.fixtures[0]),existing);
 const persisted=await p.evaluate(()=>Studio.state());await p.evaluate(d=>Studio.loadProject(d),persisted);assert.deepEqual(await p.evaluate(()=>G.fixtures),persisted.fixtures);const dl=p.waitForEvent('download');await p.evaluate(()=>pngIndir());await(await dl).saveAs('artifacts/furniture-export-5.9.13.png');
 // Every catalog symbol renders without dimension text and survives file validation.
 const allKinds=await p.evaluate(()=>{const ctx=document.createElement('canvas').getContext('2d'),text=[];ctx.fillText=t=>text.push(t);return {kinds:Object.entries(FurnitureCatalog.items).map(([kind,item])=>{const [w,d]=item.sizes[0];Fixtures.symbol(ctx,{kind,w,d,angle:90,mirror:true},50,50,.2,'white');const state=Studio.state();state.fixtures=[{id:'test',kind,w,d,x:100,y:100,angle:90,mirror:true}];return PlanProject.validate(state).fixtures[0].kind;}),text};});assert.equal(allKinds.kinds.length,10);assert.deepEqual(allKinds.text,[]);
 // Concave rooms still require the entire furniture footprint and access zone inside.
 const concave=await p.evaluate(()=>{Studio.loadProject({v:'5',n:[{id:'a',x:0,y:0},{id:'b',x:500,y:0},{id:'c',x:500,y:250},{id:'d',x:300,y:250},{id:'e',x:300,y:500},{id:'f',x:0,y:500}],s:[['a','b'],['b','c'],['c','d'],['d','e'],['e','f'],['f','a']].map(([n1,n2],i)=>({id:'s'+i,n1,n2,k:10})),e:[],r:[]});G.rooms[0].tip='cocuk';const plans=FurnitureLayout.propose(G.rooms[0]),ctx=FurnitureLayout.context(G.rooms[0]);return plans.every(p=>p.fixtures.every((f,i)=>FurnitureLayout.valid(f,p.fixtures.slice(0,i),ctx)));});assert.equal(concave,true);
 await load(90,500,'giris');assert.equal(await p.evaluate(()=>FurnitureLayout.propose(G.rooms[0]).length),0);
 await load(180,180);assert.equal(await p.evaluate(()=>FurnitureLayout.propose(G.rooms[0],{}).some(p=>p.fixtures.some(f=>f.kind==='bedDouble'))),false);
 await load(500,500,'banyo');assert.equal(await p.evaluate(()=>{try{FurnitureLayout.propose(G.rooms[0]);return false;}catch{return true;}}),true);
 assert.deepEqual(errors,[]);console.log('PASS furniture catalog, real placement, custom outer size, lock, JSON, read-only alternatives, collisions, passage, apply, undo and room types');await b.close();})().catch(e=>{console.error(e);process.exit(1)});
