const assert=require('node:assert/strict'),path=require('path');let pw;try{pw=require('playwright')}catch{pw=require(path.resolve(path.dirname(process.execPath),'../node_modules/playwright'))}
(async()=>{const b=await pw.chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{const p=await b.newPage({viewport:{width:1500,height:960}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(require('url').pathToFileURL(path.resolve('dist/plan_studio.html')).href);
for(const angle of [0,90,180,270])for(const k of [6,10,15]){
const r=await p.evaluate(({angle,k})=>{Studio.loadProject({v:'5',sistem:'prefabrik',n:[],s:[],e:[],r:[],opt:{h:250}});const z=RoofStudio.make({id:'main',group:'g',w:500,d:500,angle,h:250,wallTop:250,pitch:30,datum:'trim',fasciaDepth:12,eaves:[22,22,30,30]});G.roofs=[z];G.nodes=[{id:'a',...RoofCore.transform(z,{x:k/2,y:0})},{id:'b',...RoofCore.transform(z,{x:k/2,y:500})}];G.segs=[{id:'ab',n1:'a',n2:'b',k}];const before=JSON.stringify(Studio.state()),items=RoofStudio.planStructure().filter(f=>f.kind==='gableOmega');return{items:items.map(f=>({...f,poly:f.poly.map(p=>({...RoofCore.untransform(z,p),z:p.z}))})),unchanged:before===JSON.stringify(Studio.state())};},{angle,k});
assert.ok(r.items.length);assert.ok(r.unchanged);assert.ok(r.items.every(f=>f.widthMm===k*10&&f.sheetMm===1));
const bounds=part=>{const v=r.items.filter(f=>f.part===part).flatMap(f=>f.poly);return [Math.min(...v.map(p=>p.x)),Math.max(...v.map(p=>p.x)),Math.min(...v.map(p=>p.z)),Math.max(...v.map(p=>p.z))]};
const near=(a,b)=>a.forEach((v,i)=>assert.ok(Math.abs(v-b[i])<1e-6,JSON.stringify({a,b})));
near(bounds('outerLip'),[-1.3,-1.2,247,249]);near(bounds('innerFlange'),[k+.1,k+2.6,247,247.1]);near(bounds('top'),[-.1,k+.1,250,250.1]);
const noWalls=await p.evaluate(()=>{G.segs=[];return RoofStudio.planStructure().filter(f=>f.kind==='gableOmega').length});assert.equal(noWalls,0);
}
await p.evaluate(()=>{const z=G.roofs[0];G.nodes=[{id:'a',...RoofCore.transform(z,{x:7.5,y:0})},{id:'b',...RoofCore.transform(z,{x:7.5,y:500})}];G.segs=[{id:'ab',n1:'a',n2:'b',k:15}];RoofStudio.open();RoofStudio.setView('3d');RoofStudio.fit();});await p.screenshot({path:'artifacts/gable-omega.png'});assert.deepEqual(errors,[]);console.log('PASS omega 3 widths x 4 orientations, 1mm sheet, exterior lip/interior flange, no unsupported walls, immutable model');}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
