const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),C=require('../src/roof-core'),pw=require(path.resolve(path.dirname(process.execPath),'../node_modules/playwright'));
const source=JSON.parse(fs.readFileSync('cizimler/gulsum-84m2/veranda-kirisli-ornek-5.9.98.json'));
for(const rotation of [0,90,180,270]){const d=structuredClone(source),frame={x:0,y:0,angle:rotation};for(const z of d.roofs){Object.assign(z,C.transform(frame,z),{angle:(z.angle+rotation)%360});if(z.attachment){const b=z.attachment.base;Object.assign(b,C.transform(frame,b),{angle:(b.angle+rotation)%360});z.attachment.mode='tek';z.attachment.pitch=5;}}
 const z=C.attachVeranda(d.roofs[1],d.roofs[0]);assert.equal(z.attachmentJoin,'gable-canopy');assert.equal(z.type,'tek');assert.ok(z.frontClearance>=210);assert.ok(z.d>100);assert.ok(C.zoneFaces(z).every(f=>Math.abs(Math.hypot(f.a,f.b)-.05)<1e-6));assert.throws(()=>C.attachVeranda({...z,attachment:{...z.attachment,pitch:70}},d.roofs[0]),/ön açıklığı/);
}
(async()=>{const b=await pw.chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{const p=await b.newPage({viewport:{width:1700,height:1100}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto(require('url').pathToFileURL(path.resolve('plan_cizim.html')).href);
 await p.evaluate(d=>{d.roofs=d.roofs.slice(0,1);const z=d.roofs[0];z.w=700.25;z.outline=z.outline.map(p=>({...p,x:Math.min(p.x,700.25)}));z.boundaryRefs=undefined;Studio.loadProject(d);G.roofs.push(RoofStudio.make({x:893.5,y:695.25,w:188.25,d:391.5,angle:90,type:'besik',h:250,wallTop:250,datum:'trim',name:'Sağ çıkma çatısı'}));RoofStudio.open();},source);
 await p.selectOption('#roofVerandaType','tek');await p.selectOption('#roofVerandaBeam','all');await p.click('#roofFromVeranda');
 const r=await p.evaluate(()=>{const z=G.roofs.find(z=>z.sourceRoomId);return {z,state:Studio.state(),members:z&&RoofStudio.verandaMembers(z),shapes:z&&RoofStudio.verandaStructure(z),notice:document.getElementById('roofNotice').textContent}});assert.ok(r.z,r.notice);assert.equal(r.z.attachmentJoin,'gable-canopy');assert.equal(r.members.filter(m=>m.kind==='beam').length,3);assert.equal(r.shapes.filter(s=>s.kind==='canopyCladding').length,2);assert.ok(r.z.frontClearance>=210);
 await p.evaluate(()=>{RoofStudio.setView('3d');Camera3D.state.pitch=12;RoofStudio.repaint()});await p.screenshot({path:'artifacts/gable-canopy.png'});await p.evaluate(d=>Studio.loadProject(d),r.state);assert.equal(await p.evaluate(()=>G.roofs.find(z=>z.sourceRoomId).attachment.mode),'tek');assert.deepEqual(errors,[]);console.log('PASS gable canopy four directions, clearance rejection, real-plan shortened main roof, all beams, side cladding and JSON');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
