const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{pathToFileURL}=require('url'),Core=require('../src/loading-core.js');let pw;try{pw=require('playwright')}catch{pw=require(path.resolve(path.dirname(process.execPath),'../node_modules/playwright'))}
assert.equal(Core.cornerProduct(10,250).size,'98 × 98 × 2500 mm');
assert.equal(Core.cornerProduct('6',280).size,'58 × 58 × 2800 mm');
assert.equal(Core.cornerProduct(10,300).referenceId,'');
assert.equal(Core.cornerProduct('10/6',250),null);
assert.equal(Core.cornerProduct(15,250),null);
(async()=>{const b=await pw.chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{const p=await b.newPage();await p.goto(pathToFileURL(path.resolve('dist/plan_studio.html')).href);const data=JSON.parse(fs.readFileSync('cizimler/2026-10-02-tuna84-dwg-esleme-taslak.json'));await p.evaluate(d=>Studio.loadProject(d),data);
const result=await p.evaluate(()=>{const before=Studio.snapshot(),r=LoadingList.calculate().rows.find(r=>r.name==='Köşe direği');return {r,unchanged:before===Studio.snapshot(),nominal:pfAnaliz().bag.filter(b=>b.tip==='kose').map(b=>b.k)};});assert.ok(result.unchanged);assert.equal(result.r.qty,8);assert.equal(result.r.size,'98 × 98 × 2500 mm');assert.equal(result.r.referenceId,'tuna-22');assert.ok(result.nominal.every(k=>Number(k)===10));
await p.evaluate(()=>{const r=LoadingList.calculate().rows.find(r=>r.name==='Köşe direği');G.loading={adjustments:[{key:r.key,basis:r.basis,qty:9,reason:'Test',referenceId:r.referenceId}],manual:[]};document.getElementById('katYuk').value='280';});const changed=await p.evaluate(()=>LoadingList.calculate());assert.equal(changed.orphan.length,1);assert.equal(changed.rows.find(r=>r.name==='Köşe direği').size,'98 × 98 × 2800 mm');
const six=JSON.parse(JSON.stringify(data));six.ky=300;six.opt.h=300;six.opt.dis=6;six.opt.ic=6;six.s.forEach(s=>{if(s.tip!=='veranda'){s.k=6;s.kSabit=true;}});await p.evaluate(d=>Studio.loadProject(d),six);const sixResult=await p.evaluate(()=>({rows:LoadingList.calculate().rows.filter(r=>r.name==='Köşe direği'),nominal:pfAnaliz().bag.filter(b=>b.tip==='kose').map(b=>b.k)}));assert.ok(sixResult.rows.length>0);assert.ok(sixResult.rows.every(r=>r.size==='58 × 58 × 3000 mm'&&r.qty===r.calculated&&r.referenceId===''));assert.ok(sixResult.nominal.every(k=>Number(k)===6));
console.log('PASS corner 10/6 nominal preserved, dynamic height, eight Tuna posts, unknown profiles and stale decisions');}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
