const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{pathToFileURL}=require('url'),Core=require('../src/loading-core.js');let pw;try{pw=require('playwright')}catch{pw=require(path.resolve(path.dirname(process.execPath),'../node_modules/playwright'))}
assert.throws(()=>Core.validate({adjustments:[],manual:[{id:'x',name:'A',size:'',unit:'adet',qty:-1,reason:'test'}]}));
assert.throws(()=>Core.validate({adjustments:[],manual:[{id:'x',name:'A',size:'',unit:'adet',qty:1.5,reason:'test'}]}));
assert.match(Core.csv([{name:'=1+1',sources:[]}]),/"'=1\+1"/);
(async()=>{const b=await pw.chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{const p=await b.newPage({viewport:{width:1550,height:1050}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(pathToFileURL(path.resolve('dist/plan_studio.html')).href);const source=JSON.parse(fs.readFileSync('cizimler/2026-10-02-tuna84-dwg-esleme-taslak.json'));await p.evaluate(d=>Studio.loadProject(d),source);const before=await p.evaluate(()=>Studio.snapshot());
 await p.locator('#loadingOpen').click();let report=await p.evaluate(()=>LoadingList.calculate());assert.equal(report.rows.filter(r=>r.group==='Panel').reduce((n,r)=>n+r.calculated,0),49);assert.equal(report.rows.filter(r=>r.group==='Kapı / PVC').reduce((n,r)=>n+r.calculated,0),12);assert.ok(report.rows.every(r=>r.qty===null));assert.equal(before,await p.evaluate(()=>Studio.snapshot()));
 await p.locator('#loadGroup').selectOption('Panel');await p.locator('#loadTable [data-edit]').first().click();await p.locator('#lmQty').fill('2');await p.locator('#lmReason').fill('Kesim planı denemesi');await p.locator('#lmRef').selectOption('tuna-9');await p.locator('#loadForm button[type=submit]').click();assert.equal(await p.evaluate(()=>G.loading.adjustments.length),1);await p.evaluate(()=>geriAl());assert.equal(await p.evaluate(()=>G.loading.adjustments.length),0);await p.evaluate(()=>ileriAl());assert.equal(await p.evaluate(()=>G.loading.adjustments.length),1);
 await p.locator('#loadRefresh').click();await p.locator('#loadAdd').click();await p.locator('#lmName').fill('Vida test');await p.locator('#lmSize').fill('4,8 × 70');await p.locator('#lmQty').fill('200');await p.locator('#lmReason').fill('Montaj sorumlusu ekledi');await p.locator('#loadForm button[type=submit]').click();const saved=await p.evaluate(()=>Studio.state());assert.equal(saved.loading.manual.length,1);
 await p.locator('#loadClose').click();await p.evaluate(d=>Studio.loadProject(d),saved);assert.deepEqual(await p.evaluate(()=>Studio.state().loading),saved.loading);await p.locator('#loadingOpen').click();await p.locator('#loadGroup').selectOption('');await p.screenshot({path:'artifacts/loading-list.png'});
 const download=p.waitForEvent('download');await p.locator('#loadCsv').click();const d=await download;await d.saveAs('artifacts/loading-list.csv');const csv=fs.readFileSync('artifacts/loading-list.csv','utf8');assert.match(csv,/TASLAK/);assert.match(csv,/Vida test/);assert.match(csv,/Kural bekliyor/);assert.match(csv,/5.9.28/);assert.match(csv,/Tuna 84/);
 const stale=await p.evaluate(()=>{const c=LoadingList.calculate(),row=c.rows.find(r=>r.qty!==null&&r.group!=='Manuel'),id=row.sources[0].segIds[0],s=getSeg(id),n=getNode(s.n1);n.x+=1;const changed=LoadingList.calculate();n.x-=1;return {stale:changed.rows.some(r=>r.stale),orphan:changed.orphan.length};});assert.ok(stale.stale||stale.orphan>0);
 await p.locator('#loadTable [data-show]').first().click();assert.equal(await p.locator('#loadingDialog').evaluate(e=>e.open),false);assert.ok(await p.evaluate(()=>G.selSegs.length>0));
 const atomic=await p.evaluate(()=>{const before=Studio.snapshot(),bad=Studio.state();bad.loading.manual[0].qty=-5;try{Studio.loadProject(bad);}catch{}return before===Studio.snapshot();});assert.ok(atomic);
 await p.evaluate(()=>{G.loading.adjustments.push({key:'removed-item',basis:'old',qty:2,reason:'Eski pano',referenceId:''});});
 await p.locator('#loadingOpen').click();assert.equal(await p.locator('#loadOrphans').isVisible(),true);await p.locator('#loadOrphans summary').click();await p.locator('[data-orphan]').click();assert.equal(await p.evaluate(()=>LoadingList.calculate().orphan.length),0);await p.locator('#loadClose').click();
 await p.evaluate(()=>Studio.flush());await p.reload();await p.evaluate(()=>Studio.recover());assert.equal(await p.evaluate(()=>G.loading.manual[0].name),'Vida test');
 await p.evaluate(d=>Studio.loadProject(d),source);assert.deepEqual(await p.evaluate(()=>G.loading),{adjustments:[],manual:[]});assert.deepEqual(errors,[]);console.log('PASS 49 panel/12 opening counts, pending quantities, reference mapping, manual edit, undo/redo, JSON persistence, CSV, stale detection, source selection and atomic validation');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});

