const assert=require('node:assert/strict'),path=require('path');let pw;try{pw=require('playwright')}catch{pw=require(path.resolve(path.dirname(process.execPath),'../node_modules/playwright'))}
(async()=>{const b=await pw.chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{const p=await b.newPage({viewport:{width:1536,height:960}});await p.goto(require('url').pathToFileURL(path.resolve('dist/plan_studio.html')).href);p.on('dialog',d=>d.accept());const d={v:'5',sistem:'prefabrik',catiYon:'yatay',settings:{panelDrawMode:'mixed'},n:[{id:'a',x:0,y:0},{id:'b',x:564.75,y:0},{id:'c',x:564.75,y:512},{id:'d',x:0,y:512}],s:[['a','b'],['b','c'],['c','d'],['d','a']].map(([n1,n2],i)=>({id:'s'+i,n1,n2,k:10,kSabit:true})),e:[],r:[]};await p.evaluate(d=>{Studio.loadProject(d);G.scale=1;G.zoom=1;G.pan={x:100,y:120};draw();},d);await p.click('#panelQuickToggle');const point=async(x,y)=>p.evaluate(({x,y})=>{const q=toCv(x,y),b=cv.getBoundingClientRect();return{x:q.x+b.left,y:q.y+b.top};},{x,y});let q=await point(50,0);await p.mouse.click(q.x,q.y);assert.equal(await p.locator('#panelQuickMenu').isVisible(),true);await p.click('#panelQuickMenu [data-action=split]');assert.deepEqual(await p.evaluate(()=>pfRunOf(getSeg('s0')).run.slots.slice(0,2).map(p=>p.w)),[62.75,62.75]);q=await point(25,0);await p.mouse.click(q.x,q.y);await p.click('#panelQuickMenu [data-action=merge][data-dir="1"]');assert.equal(await p.evaluate(()=>pfRunOf(getSeg('s0')).run.slots[0].w),125.5);
// A change that removes a fixed truss support must roll back completely.
const before=await p.evaluate(()=>Studio.snapshot());q=await point(450,0);let t=await point(530,0);await p.mouse.move(q.x,q.y);await p.mouse.down();await p.mouse.move(t.x,t.y,{steps:8});await p.mouse.up();assert.equal(await p.evaluate(()=>Studio.snapshot()),before);assert.match(await p.locator('#toast').innerText(),/makas/);
// Perpendicular wall: shortened full splits on the shared half-grid and can
// exchange adjacent equal modules without relocating trusses.
await p.evaluate(()=>Prefab.select('s1',0));assert.equal(await p.evaluate(()=>Prefab.quick('split')),true);assert.deepEqual(await p.evaluate(()=>pfRunOf(getSeg('s1')).run.slots.slice(0,2).map(p=>p.w)),[62.75,62.75]);const snap=await p.evaluate(()=>Studio.snapshot());assert.equal(await p.evaluate(()=>Prefab.quick('merge',1)),true);await p.evaluate(()=>geriAl());assert.equal(await p.evaluate(()=>Studio.snapshot()),snap);await p.evaluate(()=>ileriAl());const saved=await p.evaluate(()=>Studio.state());await p.evaluate(d=>Studio.loadProject(d),saved);assert.deepEqual(await p.evaluate(()=>Modular.inspect()),[]);await p.evaluate(()=>{Prefab.select('s1',0);Prefab.quick('split');});const old=await p.evaluate(()=>Studio.snapshot()),axes=await p.evaluate(()=>makasAnaliz().makaslar.map(m=>m.pos));q=await point(564.75,100);t=await point(564.75,200);await p.mouse.move(q.x,q.y);await p.mouse.down();await p.mouse.move(t.x,t.y,{steps:8});await p.mouse.up();assert.notEqual(await p.evaluate(()=>Studio.snapshot()),old);assert.deepEqual(await p.evaluate(()=>makasAnaliz().makaslar.map(m=>m.pos)),axes);assert.deepEqual(await p.evaluate(()=>pfRunOf(getSeg('s1')).run.slots.slice(0,3).map(p=>p.w)),[62.75,125.5,62.75]);
q=await point(50,0);await p.mouse.click(q.x,q.y);await p.screenshot({path:'artifacts/panel-quick.png'});await p.evaluate(d=>{Studio.loadProject(d);Studio.edit(()=>{cizimKoseDuzelt(getNode('e12'),getNode('e27'),true);addSeg('e12','e27',10,null,true);});let id;Studio.edit(()=>{id=addSeg(addNode(1129.5,193.25),addNode(1568.75,193.25),10,null,true);});Prefab.select(id,3);},JSON.parse(require('fs').readFileSync('cizimler/2026-10-08-panel-kapanis/orijinal.json')));assert.equal(await p.evaluate(()=>Prefab.quick('split')),true,await p.locator('#toast').innerText());assert.deepEqual(await p.evaluate(()=>Prefab.resolve().run.slots.slice(-2).map(p=>p.w)),[62.75,57.75]);
console.log('panel-quick: click menu, split/merge, drag rejection with atomic rollback, undo/redo and JSON passed');}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});

