const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');let pw;try{pw=require('playwright')}catch{pw=require(path.resolve(path.dirname(process.execPath),'../node_modules/playwright'))}
(async()=>{const b=await pw.chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{const p=await b.newPage();await p.goto(require('url').pathToFileURL(path.resolve('dist/plan_studio.html')).href);const data=JSON.parse(fs.readFileSync('cizimler/2026-10-08-panel-kapanis/orijinal.json','utf8'));
for(const reverse of [false,true]){await p.evaluate(d=>Studio.loadProject(d),data);const result=await p.evaluate(reverse=>{G.tool="duvar";const before=Studio.snapshot(),nodes=JSON.stringify(G.nodes),axes=()=>pfAnaliz().runs.filter(r=>!r.makasParalel).map(r=>({id:r.owner.id,org:r.panelOrg,joints:r.slots.slice(1).map(p=>r.ay+p.a)})).sort((a,b)=>a.id.localeCompare(b.id));const old=axes(),start=getNode(reverse?'e27':'e12'),end=getNode(reverse?'e12':'e27');const preview=pfCizimOnizleme(start,end);const unchanged=Studio.snapshot()===before;const ok=Studio.edit(()=>{cizimKoseDuzelt(start,end,true);addSeg(start.id,end.id,10,null,true);});const after=Studio.snapshot(),saved=Studio.state(),next=axes(),issues=Modular.inspect();geriAl();const undo=Studio.snapshot()===before;ileriAl();const redo=Studio.snapshot()===after;Studio.loadProject(saved);return{ok,unchanged,undo,redo,old,next,issues,nodesStable:JSON.stringify(G.nodes)===nodes,reloaded:axes(),preview:preview.slots.map(p=>p.w)};},reverse);assert.equal(result.ok,true,JSON.stringify(result));for(const k of ['unchanged','undo','redo','nodesStable'])assert.equal(result[k],true,k);assert.deepEqual(result.issues,[]);assert.deepEqual(result.old,result.next);assert.deepEqual(result.next,result.reloaded);assert.deepEqual(result.preview.slice().sort((a,b)=>a-b),[62.75,125.5,125.5,125.5]);}
await p.evaluate(d=>Studio.loadProject(d),data);await p.locator('#t-duvar').click();await p.evaluate(()=>{G.scale=1;G.zoom=.45;G.pan={x:40,y:140};draw();});
for(const id of ['e12','e27']){const point=await p.evaluate(id=>{const n=getNode(id),p=toCv(n.x,n.y),b=cv.getBoundingClientRect();return{x:p.x+b.left,y:p.y+b.top};},id);await p.mouse.click(point.x,point.y);}
assert.equal(await p.evaluate(()=>G.rooms.length),1);assert.equal(await p.evaluate(()=>G.segs.length),8);assert.deepEqual(await p.evaluate(()=>Modular.inspect()),[]);await p.keyboard.press('Escape');await p.screenshot({path:'artifacts/panel-close.png'});
await p.evaluate(()=>{getNode('e27').x+=13;});assert.ok((await p.evaluate(()=>Modular.inspect())).length>0);console.log('panel-close: both directions, preview, fixed H axes, nodes, undo/redo, JSON and invalid dimensions passed');}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});


