const assert=require('node:assert/strict'),path=require('node:path'),C=require('../src/roof-core.js');
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`),layer=id=>({...C.LAYERS.find(l=>l.id===id),fire:0});
const z=C.defaults({id:'main',h:250,datum:'eave',layers:[layer('osb'),layer('nem'),layer('membran')]});
for(const material of ['trapez','sandvic','tekkat','metal','shingle']){const m=C.calculate([{...z,material}]);assert.equal(m.layerTotals.length,3);m.layerTotals.forEach(t=>near(t.netArea,m.area));for(const id of ['osb','nem','membran'])near(m.layerCuts.filter(c=>c.layer===id).reduce((s,c)=>s+c.polygons.reduce((v,p)=>v+C.area(p),0),0)/10000,m.planArea);}
assert.equal(C.calculate([C.defaults()],[],true).layerTotals.length,1);assert.equal(C.calculate([C.defaults({layers:[]})],[],true).layerTotals.length,0);
assert.throws(()=>C.calculate([{...z,layers:[{...layer('osb'),overlapWidth:122}]}]));
const base={x:850,y:1100,w:600,d:300,angle:180,eaves:[30,30,30,0]},porch=C.attachVeranda(C.defaults({id:'veranda',sourceRoomId:'r1',layers:[layer('osb')],attachment:{parentId:'main',mode:'besik',base,pitch:33,gap:10,minClearance:210}}),z),m=C.calculate([z,porch]);
for(const row of [...m.cutList,...m.layerCuts])for(const poly of row.polygons)for(const p of poly)assert.ok(m.faces.some(f=>f.zoneId===row.zoneId&&C.contains(f.poly,p)));
(async()=>{let pw;try{pw=require('playwright')}catch{pw=require(path.resolve(path.dirname(process.execPath),'../node_modules/playwright'))}const b=await pw.chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{const p=await b.newPage({viewport:{width:1700,height:1100}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(require('url').pathToFileURL(path.resolve('dist/plan_studio.html')).href);await p.evaluate(({z,porch})=>{Studio.loadProject({v:'5',n:[],s:[],e:[],r:[],roofs:[z,porch]});RoofStudio.open();RoofStudio.select('veranda');}, {z,porch});
await p.check('[name="layer_membran"]');await p.check('[name="layer_nem"]');await p.fill('#rz_layer_osb_fire','10');await p.click('#roofApply');assert.equal(await p.evaluate(()=>G.roofs[1].layers.length),3);assert.ok(await p.evaluate(()=>RoofStudio.model().layerTotals.find(t=>t.zoneId==='veranda'&&t.layer==='osb').quantity>RoofStudio.model().layerTotals.find(t=>t.zoneId==='veranda'&&t.layer==='osb').pieces));
await p.selectOption('#roofLayoutLayer','osb');await p.waitForTimeout(100);await p.screenshot({path:'artifacts/roof-osb-layout.png'});
await p.locator('[data-layer="membran"] [data-layer-move="-1"]').click();await p.click('#roofApply');assert.deepEqual(await p.evaluate(()=>G.roofs[1].layers.map(l=>l.id)),['osb','membran','nem']);
await p.selectOption('#rz_material','shingle');await p.click('#roofApply');assert.equal(await p.evaluate(()=>RoofStudio.model().layerTotals.filter(t=>t.zoneId==='veranda').length),3);assert.ok(await p.evaluate(()=>RoofStudio.model().totals.some(t=>t.material==='shingle'&&t.packages>0)));
await p.uncheck('[name="layer_osb"]');await p.click('#roofApply');assert.equal(await p.evaluate(()=>RoofStudio.model().layerTotals.some(t=>t.zoneId==='veranda'&&t.layer==='osb')),false);await p.click('#roofUndo');assert.equal(await p.evaluate(()=>G.roofs[1].layers.some(l=>l.id==='osb')),true);
const saved=await p.evaluate(()=>Studio.state());await p.evaluate(d=>Studio.loadProject(d),saved);assert.deepEqual(await p.evaluate(()=>G.roofs[1].layers.map(l=>l.id)),['osb','membran','nem']);assert.match(await p.evaluate(()=>RoofStudio.csv()),/Nem bariyeri/);assert.ok(await p.evaluate(()=>RoofStudio.billRows().some(r=>r.kalem.includes('Membran'))));await p.evaluate(()=>{RoofStudio.open();RoofStudio.setView('report');});assert.match(await p.locator('#roofReport').innerText(),/Alt katmanlar/);assert.deepEqual(errors,[]);console.log('PASS independent layers under every cover, clipped panel polygons, overlap validation, legacy OSB migration, ordering, fire, toggle, undo, JSON, report and CSV');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
