const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');let pw;try{pw=require('playwright')}catch{pw=require(path.resolve(path.dirname(process.execPath),'../node_modules/playwright'))}
(async()=>{const b=await pw.chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{const p=await b.newPage({viewport:{width:1800,height:1150}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(require('url').pathToFileURL(path.resolve('dist/plan_studio.html')).href);await p.evaluate(d=>{Studio.loadProject(d);RoofStudio.open();RoofStudio.setView('3d');},JSON.parse(fs.readFileSync('cizimler/2026-10-08-omega-aciklik/orijinal.json')));
const before=await p.evaluate(()=>JSON.stringify(Studio.state()));let stats=await p.evaluate(()=>({...Scene3D.stats}));assert.equal(stats.backend,'webgl');assert.ok(stats.triangles>0&&stats.lines>0);assert.ok(stats.antialias);console.log(stats);await p.screenshot({path:'artifacts/gpu-roof.png'});await p.click('#roofHide');await p.selectOption('#roofProjection','perspective');await p.screenshot({path:'artifacts/gpu-panels.png'});
await p.click('#roofTheme');assert.equal(await p.evaluate(()=>Scene3D.state.theme),'dark');await p.click('#roofContours');assert.equal(await p.evaluate(()=>Scene3D.state.outlines),false);await p.click('#roofContours');await p.click('#roofTheme');
for(const view of ['front','back','left','right','top','iso']){await p.selectOption('#roofViewpoint',view);assert.equal(await p.evaluate(()=>Scene3D.stats.backend),'webgl');}
assert.equal(await p.evaluate(()=>JSON.stringify(Studio.state())),before);
await p.evaluate(()=>{Studio.loadProject({v:'5',sistem:'prefabrik',n:[{id:'a',x:0,y:0},{id:'b',x:500,y:0}],s:[{id:'ab',n1:'a',n2:'b',k:10}],e:[{id:'w',segId:'ab',t:.3,en:160,yuk:120,tip_:'pencere'}],r:[],opt:{h:250}});RoofStudio.open();RoofStudio.setView('3d');});await p.screenshot({path:'artifacts/gpu-stl.png'});assert.equal(await p.evaluate(()=>Scene3D.stats.backend),'webgl');assert.ok(await p.evaluate(()=>Wall3D.build().surfaces.some(s=>s.material==='glass')));console.log('STL',await p.evaluate(()=>({...Scene3D.stats})));
const download=p.waitForEvent('download');await p.click('#roofPNG');const file=await(await download).path();assert.equal(fs.readFileSync(file).subarray(1,4).toString(),'PNG');
const fallback=await b.newPage();await fallback.addInitScript(()=>{const get=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return type==='webgl'?null:get.call(this,type,...args)};});await fallback.goto(require('url').pathToFileURL(path.resolve('dist/plan_studio.html')).href);await fallback.evaluate(()=>{RoofStudio.open();RoofStudio.setView('3d');});assert.notEqual(await fallback.evaluate(()=>Scene3D.stats.backend),'webgl');await fallback.close();assert.deepEqual(errors,[]);console.log('PASS GPU antialias, real roof/panels, STL glass, all cameras, themes/contours, PNG, model unchanged and no-WebGL fallback');}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
