const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{pathToFileURL}=require('url');let pw;try{pw=require('playwright')}catch{pw=require(path.resolve(path.dirname(process.execPath),'../node_modules/playwright'))}
const Project=require('../src/project.js');
(async()=>{const b=await pw.chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{const p=await b.newPage({viewport:{width:1600,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(pathToFileURL(path.resolve('plan_cizim.html')).href);
 const source=JSON.parse(fs.readFileSync('cizimler/2026-10-02-is-kayit-5.json'));await p.evaluate(d=>Studio.loadProject(d),source);const before=await p.evaluate(()=>Studio.state());
 await p.locator('#t-text').click();await p.locator('#noteText').fill('Profilden\nMontaj notu <b>');await p.locator('#noteSize').fill('14');await p.locator('#noteSubmit').click();const box=await p.locator('#cv').boundingBox();await p.mouse.click(box.x+200,box.y+160);
 let d=await p.evaluate(()=>Studio.state());assert.equal(d.annotations.length,1);assert.equal(d.annotations[0].text,'Profilden\nMontaj notu <b>');assert.deepEqual(d.s,before.s);assert.deepEqual(d.e,before.e);Project.validate(d);
 const a=d.annotations[0];await p.mouse.move(box.x+205,box.y+165);await p.mouse.down();await p.mouse.move(box.x+255,box.y+195);await p.mouse.up();d=await p.evaluate(()=>Studio.state());assert.notEqual(d.annotations[0].x,a.x);await p.evaluate(()=>geriAl());assert.deepEqual((await p.evaluate(()=>Studio.state())).annotations[0],a);await p.evaluate(()=>ileriAl());
 const pos=await p.evaluate(()=>{const a=G.annotations[0],p=toCv(a.x,a.y),r=cv.getBoundingClientRect();return{x:p.x+r.left+2,y:p.y+r.top+2}});await p.mouse.dblclick(pos.x,pos.y);await p.locator('#noteText').fill('Düzeltilmiş not');await p.locator('#noteAngle').fill('90');await p.locator('#noteSubmit').click();d=await p.evaluate(()=>Studio.state());assert.equal(d.annotations[0].angle,90);assert.equal(d.annotations[0].text,'Düzeltilmiş not');
 await p.evaluate(d=>Studio.loadProject(d),d);assert.deepEqual((await p.evaluate(()=>Studio.state())).annotations,d.annotations);
 const download=p.waitForEvent('download');await p.evaluate(()=>pngIndir());await p.locator('#exportSubmit').click();assert.match((await download).suggestedFilename(),/\.png$/);assert.deepEqual((await p.evaluate(()=>Studio.state())).annotations,d.annotations);
 await p.evaluate(()=>{G.secili=G.annotations[0];G.seciliTip='annotation';seciliSil()});assert.equal(await p.evaluate(()=>G.annotations.length),0);await p.evaluate(()=>geriAl());assert.equal(await p.evaluate(()=>G.annotations.length),1);
 const invalid=structuredClone(d);invalid.annotations[0].size=-1;assert.throws(()=>Project.validate(invalid),/Metin/);const duplicate=structuredClone(d);duplicate.annotations.push(duplicate.annotations[0]);assert.throws(()=>Project.validate(duplicate),/Tekrarlanan/);
 await p.evaluate(d=>Studio.loadProject(d),source);assert.equal(await p.evaluate(()=>G.annotations.length),0);assert.deepEqual(errors,[]);console.log('PASS text placement, move/undo/redo, edit/rotate, JSON roundtrip, PNG, delete/undo, old files, schema and unchanged walls/openings');
 }finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
