const assert=require('node:assert/strict'),path=require('node:path'),C=require('../src/roof-core.js');
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`);
const parent=C.defaults({id:'main',group:'main',x:0,y:0,w:1024,d:1139.5,h:250,datum:'eave'});
const base={x:960,y:1578.75,w:680,d:439.25,angle:180,eaves:[30,30,30,30]};
const raw=mode=>C.defaults({id:'porch',sourceRoomId:'veranda',floorLevel:0,attachment:{parentId:'main',mode,base,pitch:mode==='tek'?5:33,gap:10,minClearance:210}});
for(const rotation of [0,90,37]){
 const frame={x:500,y:100,angle:rotation},p0=C.transform(frame,parent),b0=C.transform(frame,base),host={...parent,x:p0.x,y:p0.y,angle:rotation};
 const input=raw('karga');input.attachment.base={...base,x:b0.x,y:b0.y,angle:(180+rotation)%360};
 const z=C.attachVeranda(input,host),f=C.zoneFaces(z)[0],match=C.zoneFaces(host).find(g=>Math.abs(g.a-f.a)<1e-6&&Math.abs(g.b-f.b)<1e-6);assert.ok(match);near(f.c,match.c);assert.equal(z.group,host.group);
}
const canopy=C.attachVeranda(raw('tek'),parent);near(canopy.frontClearance,250-10-(439.25-30+30)*.05);assert.equal(canopy.group,'porch');near(C.height(C.zoneFaces(canopy)[0],C.transform(canopy,{x:canopy.w/2,y:canopy.d})),240);
assert.throws(()=>C.attachVeranda({...raw('tek'),attachment:{...raw('tek').attachment,pitch:33}},parent),/ön açıklığı/);
const gable=C.attachVeranda(raw('besik'),parent),model=C.calculate([parent,gable]);assert.equal(gable.group,'main');assert.ok(gable.w>base.d);assert.ok(model.lengths.valley>0);assert.ok(!model.lengths.step);assert.ok(model.area<C.calculate([parent,{...gable,group:'other'}]).area);
(async()=>{let pw;try{pw=require('playwright')}catch{pw=require(path.resolve(path.dirname(process.execPath),'../node_modules/playwright'))}const b=await pw.chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{const p=await b.newPage({viewport:{width:1700,height:1100}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(require('url').pathToFileURL(path.resolve('dist/plan_studio.html')).href);
await p.evaluate(()=>{const n=[{id:'a',x:0,y:0},{id:'b',x:1024,y:0},{id:'c',x:1024,y:1139.5},{id:'d',x:0,y:1139.5},{id:'e',x:344,y:1139.5},{id:'f',x:1024,y:1578.75},{id:'g',x:344,y:1578.75}];const edges=[['a','b'],['b','c'],['c','e'],['e','d'],['d','a'],['c','f'],['f','g'],['g','e']];Studio.loadProject({v:'5',n,s:edges.map(([n1,n2],i)=>({id:'s'+i,n1,n2,k:10,tip:i>=5?'veranda':undefined})),e:[],r:[]});G.rooms.find(r=>r.area<40).tip='veranda';RoofStudio.open();RoofStudio.add(RoofStudio.make({x:0,y:0,w:1024,d:1139.5,type:'besik',h:250,wallTop:250}));});
assert.equal(await p.locator('#roofNewType').isVisible(),false);
for(const mode of ['tek','karga','besik']){await p.selectOption('#roofVerandaType',mode);await p.click('#roofFromVeranda');assert.equal(await p.evaluate(()=>G.roofs.length),2);assert.equal(await p.evaluate(()=>G.roofs[1].attachment.mode),mode);const structure=await p.evaluate(()=>RoofStudio.verandaStructure(G.roofs[1]));assert.equal(structure.filter(s=>s.kind==='post').length,8);assert.equal(structure.filter(s=>s.kind==='cladding').length,mode==='besik'?1:0);assert.ok(structure.every(s=>['post','cladding','gableCornerClosure'].includes(s.kind)));await p.evaluate(()=>RoofStudio.setView('3d'));await p.waitForTimeout(150);await p.screenshot({path:'artifacts/veranda-'+mode+'.png'});}
await p.click('#roofUndo');assert.equal(await p.evaluate(()=>G.roofs[1].attachment.mode),'karga');await p.click('#roofRedo');assert.equal(await p.evaluate(()=>G.roofs[1].attachment.mode),'besik');
await p.selectOption('#roofVerandaType','tek');await p.click('#roofFromVeranda');const before=await p.evaluate(()=>JSON.stringify(G.roofs));await p.fill('#rz_link_pitch','33');await p.click('#roofApply');assert.equal(await p.evaluate(()=>JSON.stringify(G.roofs)),before);assert.match(await p.locator('#roofNotice').innerText(),/ön açıklığı/);
await p.fill('#rz_link_pitch','4');await p.click('#roofApply');assert.equal(await p.evaluate(()=>G.roofs[1].pitch),4);
const saved=await p.evaluate(()=>Studio.state());await p.evaluate(d=>Studio.loadProject(d),saved);assert.equal(await p.evaluate(()=>G.roofs[1].attachment.pitch),4);await p.evaluate(()=>{RoofStudio.open();RoofStudio.select(G.roofs[0].id);});await p.fill('#rz_wallTop','270');await p.click('#roofApply');assert.ok(await p.evaluate(()=>G.roofs[1].frontClearance>240));
assert.deepEqual(errors,[]);console.log('PASS veranda plane continuation, attached gable valleys, canopy clearance, open posts/cladding, update-in-place, undo/redo, persistence and parent updates');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
