const fs=require('fs'),assert=require('node:assert/strict'),path=require('path'),{pathToFileURL}=require('url'),V=require('../src/veranda-core.js');let pw;try{pw=require('playwright')}catch{pw=require(path.resolve(path.dirname(process.execPath),'../node_modules/playwright'))}
const source=JSON.parse(fs.readFileSync('cizimler/2026-10-02-tuna84-dwg-esleme-taslak.json'));
const near=(a,b)=>assert.ok(Math.abs(a-b)<.01,`${a} != ${b}`);
const walls=d=>({walls:d.s.filter(s=>s.tip!=='veranda'),nodes:d.n.filter(n=>d.s.some(s=>s.tip!=='veranda'&&(s.n1===n.id||s.n2===n.id))),openings:d.e});
near(V.measure(source,'cadPorchLeft'),69.5);near(V.measure(source,'cadPorchFront'),507);
const deep=V.resize(source,'cadPorchLeft',100,'start');near(V.measure(deep.state,'cadPorchLeft'),100);near(V.measure(deep.state,'cadPorchFront'),507);assert.deepEqual(walls(deep.state),walls(source));assert.equal(deep.steps,0);
const wide=V.resize(source,'cadPorchFront',550,'start');near(V.measure(wide.state,'cadPorchFront'),550);assert.equal(wide.steps,1);assert.deepEqual(walls(wide.state),walls(source));
const free={v:'5',n:[{id:'a',x:0,y:0},{id:'b',x:100,y:0},{id:'c',x:100,y:100},{id:'d',x:0,y:100}],s:[{id:'ab',n1:'a',n2:'b',k:10,tip:'veranda'},{id:'bc',n1:'b',n2:'c',k:10,tip:'veranda'},{id:'cd',n1:'c',n2:'d',k:10,tip:'veranda'},{id:'da',n1:'d',n2:'a',k:10,tip:'veranda'}],e:[],r:[]};const restored=V.resize(wide.state,'cadPorchFront',507,'start');near(V.measure(restored.state,'cadPorchFront'),507);assert.equal(restored.state.s.length,source.s.length);assert.deepEqual(walls(restored.state),walls(source));const mid=V.resize(free,'ab',140,'center');near(mid.state.n[0].x,-20);near(mid.state.n[1].x,120);near(V.measure(mid.state,'ab'),140);
assert.throws(()=>V.resize(source,'cadPorchLeft',100,'end'),/ev duvarına bağlı/);assert.throws(()=>V.resize(source,'cadPorchFront',450,'start'),/çakışıyor/);
(async()=>{const b=await pw.chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{const p=await b.newPage({viewport:{width:1700,height:1100}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(pathToFileURL(path.resolve('plan_cizim.html')).href);await p.evaluate(d=>Studio.loadProject(d),source);const original=await p.evaluate(()=>Studio.state());
 await p.evaluate(()=>{G.secili=getSeg('cadPorchLeft');G.seciliTip='seg';updateSidebar()});await p.locator('#verandaEditMeasure').click();assert.equal(await p.locator('#verandaNet').inputValue(),'69.5');await p.locator('#verandaNet').fill('100');await p.locator('#verandaApply').click();let d=await p.evaluate(()=>Studio.state());near(V.measure(d,'cadPorchLeft'),100);assert.deepEqual(walls(d),walls(original));assert.equal(d.r.length,original.r.length);
 await p.evaluate(()=>geriAl());near(V.measure(await p.evaluate(()=>Studio.state()),'cadPorchLeft'),69.5);await p.evaluate(()=>ileriAl());near(V.measure(await p.evaluate(()=>Studio.state()),'cadPorchLeft'),100);
 await p.evaluate(d=>Studio.loadProject(d),source);const hit=await p.evaluate(()=>{draw();const h=G._dimHits.find(h=>h.segId==='cadPorchFront'),r=cv.getBoundingClientRect();return {x:r.left+h.tx,y:r.top+h.ty}});await p.mouse.dblclick(hit.x,hit.y);assert.equal(await p.locator('#verandaMeasureDialog').evaluate(e=>e.open),true);await p.locator('#verandaNet').fill('550');await p.locator('#verandaFixed').selectOption('start');assert.match(await p.locator('#verandaPreview').innerText(),/1 ev bağlantısında/);await p.locator('#verandaApply').click();d=await p.evaluate(()=>Studio.state());near(V.measure(d,'cadPorchFront'),550);assert.deepEqual(walls(d),walls(original));assert.equal(d.r.length,original.r.length);
 await p.evaluate(d=>Studio.loadProject(d),d);near(V.measure(await p.evaluate(()=>Studio.state()),'cadPorchFront'),550);assert.deepEqual(walls(await p.evaluate(()=>Studio.state())),walls(original));assert.deepEqual(errors,[]);console.log('PASS net 69.5/507, depth, width, centre, protected walls/openings, step preview, collision rejection, dimension double click, undo/redo, rooms and JSON');
 }finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
