const assert=require('node:assert/strict'),path=require('path'),{pathToFileURL}=require('url');let pw;try{pw=require('playwright')}catch{pw=require(path.resolve(path.dirname(process.execPath),'../node_modules/playwright'))}
(async()=>{const b=await pw.chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{const p=await b.newPage({viewport:{width:1550,height:1050}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(pathToFileURL(path.resolve('dist/plan_studio.html')).href);
await p.evaluate(()=>{Studio.loadProject({v:'5',sistem:'prefabrik',n:[{id:'a',x:0,y:0},{id:'b',x:261,y:0},{id:'c',x:261,y:271}],s:[{id:'ab',n1:'a',n2:'b',k:10},{id:'bc',n1:'b',n2:'c',k:10}],e:[],r:[],opt:{h:280}});RoofStudio.open();RoofStudio.add(RoofStudio.make({w:300,d:300}));RoofStudio.setView('3d');});
const result=await p.evaluate(()=>{const before=JSON.stringify(Studio.state()),a=Wall3D.build();return {parts:a.parts,surfaces:a.surfaces,unchanged:before===JSON.stringify(Studio.state()),slots:pfAnaliz().runs.reduce((n,r)=>n+r.slots.length,0)}});assert.ok(result.unchanged);assert.equal(result.parts.filter(x=>x.kind==='wallPanel').length,result.slots);assert.ok(result.parts.some(x=>x.widthMm===1250));assert.ok(result.parts.filter(x=>x.thicknessMm).every(x=>Math.abs(x.thicknessMm-96)<.001));assert.ok(result.parts.some(x=>x.jointType==='H'));assert.ok(result.parts.some(x=>x.jointType==='kose'));assert.ok(result.surfaces.every(x=>x.poly.every(v=>Number.isFinite(v.x+v.y+v.z))));
await p.evaluate(()=>{G.elemanlar.push({id:'win',segId:'ab',t:.1,en:119,yuk:120,tip_:'pencere',penTip:'cift-kanat'},{id:'door',segId:'bc',t:.3,en:80,yuk:210,tip_:'kapi'});});
const openings=await p.evaluate(()=>{const m=Wall3D.build();return {parts:m.parts.filter(x=>x.kind==='opening'),blocked:m.surfaces.some(x=>x.kind==='wallPanel'&&x.poly.every(v=>v.x>26.1&&v.x<145.1&&v.z>90&&v.z<210))};});assert.equal(openings.parts.length,2);assert.equal(openings.parts.find(x=>x.openingId==='win').sillMm,900);assert.equal(openings.parts.find(x=>x.openingId==='win').cols,2);assert.equal(openings.parts.find(x=>x.openingId==='door').sillMm,0);assert.equal(openings.blocked,false);
await p.selectOption('#roofViewpoint','front');assert.equal(await p.evaluate(()=>Camera3D.state.pitch),0);await p.selectOption('#roofViewpoint','top');assert.equal(await p.evaluate(()=>Camera3D.state.pitch),90);await p.selectOption('#roofProjection','perspective');assert.equal(await p.evaluate(()=>Camera3D.state.projection),'perspective');await p.click('#roofZoomIn');assert.ok(await p.evaluate(()=>Camera3D.state.zoom>1));await p.click('#roofFit');assert.equal(await p.evaluate(()=>Camera3D.state.zoom),1);await p.selectOption('#roofViewpoint','iso');
const cameraMath=await p.evaluate(()=>{const points=[{x:-100,y:-100,z:-100},{x:100,y:100,z:100}];Camera3D.preset('front');Camera3D.state.projection='parallel';let f=Camera3D.project(points,500,500);const parallel=[f({x:50,y:50,z:0}).x,f({x:50,y:-50,z:0}).x];Camera3D.state.projection='perspective';f=Camera3D.project(points,500,500);const perspective=[f({x:50,y:50,z:0}).x,f({x:50,y:-50,z:0}).x];return{parallel,perspective}});assert.equal(cameraMath.parallel[0],cameraMath.parallel[1]);assert.ok(cameraMath.perspective[0]>cameraMath.perspective[1]);await p.selectOption('#roofViewpoint','iso');
const canvas=await p.locator('#roofCanvas').boundingBox();const prior=await p.evaluate(()=>Camera3D.state.pitch);await p.mouse.move(canvas.x+100,canvas.y+150);await p.mouse.down();await p.mouse.move(canvas.x+140,canvas.y+170);await p.mouse.up();assert.notEqual(await p.evaluate(()=>Camera3D.state.pitch),prior);
const turns=await p.evaluate(()=>{const a=Wall3D.build().parts.find(x=>x.jointType==='kose').rect;G.catiYon=G.catiYon==='yatay'?'dikey':'yatay';const b=Wall3D.build().parts.find(x=>x.jointType==='kose').rect;return {a,b}});assert.equal(turns.a.w,turns.b.h);assert.equal(turns.a.h,turns.b.w);
await p.click('#roofHide');assert.equal(await p.locator('#roofHide').innerText(),'Çatıyı göster');await p.screenshot({path:'artifacts/wall-3d.png'});const layers=await p.evaluate(()=>{const out=[];for(const k of [6,15]){G.segs.forEach(s=>s.k=k);out.push(Wall3D.build().parts.filter(p=>p.thicknessMm).map(p=>p.thicknessMm));}return out});assert.ok(layers[0].length&&layers[1].length);assert.ok(layers[0].every(t=>Math.abs(t-56)<.001));assert.ok(layers[1].every(t=>Math.abs(t-146)<.001));const joins=await p.evaluate(()=>{Studio.loadProject({v:'5',sistem:'prefabrik',n:[{id:'a',x:0,y:0},{id:'b',x:125.5,y:0},{id:'c',x:251,y:0},{id:'d',x:125.5,y:150}],s:[{id:'ab',n1:'a',n2:'b',k:10},{id:'bc',n1:'b',n2:'c',k:10},{id:'bd',n1:'b',n2:'d',k:6}],e:[],r:[]});return {expected:pfAnaliz().bag.map(j=>j.tip),actual:Wall3D.build().parts.filter(p=>p.kind==='wallJoint').map(p=>p.jointType)}});assert.ok(joins.expected.includes('H3'));assert.deepEqual(joins.actual.sort(),joins.expected.sort());assert.deepEqual(errors,[]);console.log('PASS plan-derived panel counts,1250/96mm geometry,layers,H,corner rotation,no model mutation and roof hide');}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
