(function(){
 'use strict';const $=id=>document.getElementById(id),cat=FurnitureCatalog.items;let plans=[],index=0,baseline='',busy=false;
 const button=document.createElement('button');button.id='t-furniture';button.className='t';button.textContent='Tefriş';document.querySelector('.tool-group').append(button);
 const menu=document.createElement('dialog');menu.id='furnitureMenu';menu.innerHTML='<h3>Tefriş</h3><button class="sib" id="furnitureAuto">Odaya göre otomatik yerleşim</button><p>Elle yerleştirmek için bir ürün seçin. Ölçüler ürünün dıştan dışa kapladığı alandır.</p><div id="furnitureCatalog" style="display:grid;grid-template-columns:repeat(2,1fr);gap:8px"></div><button class="sib" data-close>Kapat</button>';
 const auto=document.createElement('dialog');auto.id='furnitureAutoDialog';auto.innerHTML='<h3>Otomatik tefriş · önizleme</h3><label>Oda<select id="furnitureRoom"></select></label><label id="furnitureBedLabel">Yatak<select id="furnitureBed"><option value="double">Çift kişilik</option><option value="single">Tek kişilik</option></select></label><label id="furnitureZoneLabel">Bölüm<select id="furnitureZone"><option value="living">Oturma bölümü</option><option value="kitchen">Mutfak bölümü</option></select></label><label id="furnitureShapeLabel">Tezgâh<select id="furnitureShape"><option value="straight">Düz</option><option value="L">L</option></select></label><p>Mevcut eşyalar korunur. Kapı önü, pencere erişimi ve 60 cm geçiş arayan öneriler sunulur. Sığmayan parçalar listelenir; Uygula demeden plan değişmez.</p><button class="sib" id="furnitureGenerate">Yerleşim öner</button><p id="furnitureResult" role="status"></p><canvas id="furniturePreview" width="680" height="390" style="width:100%;background:#101b29;border-radius:8px"></canvas><p id="furnitureMissing"></p><button class="sib" id="furnitureNext">Diğer alternatif</button><button class="sib" id="furnitureApply">Uygula</button><button class="sib" data-close>Vazgeç</button>';
 for(const d of [menu,auto]){d.style.cssText='background:#192334;color:#c5d6e6;border:1px solid #40566b;border-radius:12px;padding:20px;margin:auto;width:min(720px,90vw);max-height:88vh;overflow:auto';document.body.append(d);d.querySelector('[data-close]').onclick=()=>d.close();d.querySelectorAll('select').forEach(e=>e.style.cssText='display:block;width:100%;padding:8px;margin:6px 0 10px;background:#101b29;color:#d6e6ef;border:1px solid #40566b');}
 for(const [kind,item] of Object.entries(cat)){const b=document.createElement('button');b.className='sib';b.dataset.furniture=kind;b.style.height='110px';const canvas=document.createElement('canvas');canvas.width=180;canvas.height=70;b.append(canvas,document.createElement('br'),document.createTextNode(item.name));$('furnitureCatalog').append(b);const [w,d]=item.sizes[0];Fixtures.symbol(canvas.getContext('2d'),{kind,w,d,angle:0,mirror:false},90,35,Math.min(140/w,62/d),'#c5d6e6');b.onclick=()=>{menu.close();Fixtures.openKind(kind);};}
 button.onclick=()=>menu.showModal();$('furnitureAuto').onclick=()=>{menu.close();openAuto();};
 function settings(){const room=G.rooms.find(r=>r.id===$('furnitureRoom').value),type=room?.tip;$('furnitureBedLabel').hidden=!['yatak','ebeveyn','cocuk'].includes(type);$('furnitureZoneLabel').hidden=type!=='salon_mutfak';$('furnitureShapeLabel').hidden=type!=='mutfak'&&!(type==='salon_mutfak'&&$('furnitureZone').value==='kitchen');return room;}
 function clear(){plans=[];index=0;$('furnitureApply').disabled=true;$('furnitureNext').disabled=true;$('furnitureResult').textContent='Seçenekleri belirleyip Yerleşim öner düğmesine basın.';$('furnitureMissing').textContent='';$('furniturePreview').getContext('2d').clearRect(0,0,680,390);}
 function openAuto(room){$('furnitureRoom').replaceChildren();for(const r of G.rooms.filter(r=>!['banyo','ebanyo','wc'].includes(r.tip))){const o=document.createElement('option');o.value=r.id;o.textContent=roomLabel(r);$('furnitureRoom').append(o);}if(room)$('furnitureRoom').value=room.id;const selected=settings();$('furnitureBed').value=selected?.tip==='cocuk'?'single':'double';clear();auto.showModal();}
 for(const id of ['furnitureRoom','furnitureBed','furnitureZone','furnitureShape'])$(id).onchange=()=>{settings();if(id==='furnitureRoom')$('furnitureBed').value=settings()?.tip==='cocuk'?'single':'double';clear();};
 $('furnitureGenerate').onclick=async()=>{if(busy)return;const room=settings();if(!room){$('furnitureResult').textContent='Önce kapalı bir oda çizin ve türünü belirleyin.';return;}busy=true;clear();$('furnitureGenerate').disabled=true;$('furnitureResult').textContent='Yerleşimler ve geçişler kontrol ediliyor…';await new Promise(r=>setTimeout(r,30));try{baseline=Studio.snapshot();plans=FurnitureLayout.propose(room,{bed:$('furnitureBed').value,shape:$('furnitureShape').value,zone:room.tip==='salon_mutfak'?$('furnitureZone').value:undefined});index=0;if(!plans.length){$('furnitureResult').textContent='Bu ölçüler ve mevcut eşyalarla uygun öneri bulunamadı. Elle yerleşim veya daha küçük ürün ölçüsü kullanabilirsiniz.';}else render();}catch(e){$('furnitureResult').textContent=e.message;}finally{busy=false;$('furnitureGenerate').disabled=false;}};
 function render(){const plan=plans[index],room=G.rooms.find(r=>r.id===plan.roomId);if(!plan||!room)return;const ctx=FurnitureLayout.context(room),canvas=$('furniturePreview'),c=canvas.getContext('2d'),x0=Math.min(...ctx.poly.map(p=>p.x)),y0=Math.min(...ctx.poly.map(p=>p.y)),w=Math.max(...ctx.poly.map(p=>p.x))-x0,h=Math.max(...ctx.poly.map(p=>p.y))-y0,s=Math.min(620/w,330/h),ox=(680-w*s)/2,oy=(390-h*s)/2;
   c.clearRect(0,0,680,390);function poly(points,color,fill){c.beginPath();points.forEach((p,i)=>{const x=ox+(p.x-x0)*s,y=oy+(p.y-y0)*s;i?c.lineTo(x,y):c.moveTo(x,y);});c.closePath();c.strokeStyle=color;c.lineWidth=1.5;if(fill){c.fillStyle=fill;c.fill();}c.stroke();}
   poly(ctx.poly,'#b6cddd');ctx.doors.forEach(p=>poly(p,'#d69d65','#d69d6518'));ctx.windows.forEach(p=>poly(p,'#6caccc'));
   (G.counters||[]).forEach(a=>{if(FurnitureLayout.overlap(a.points,ctx.poly))poly(a.points,'#71879a');});plan.counters.forEach(a=>{const shape=CounterCut.difference(a.points,[...(G.fixtures||[]),...plan.fixtures].filter(f=>f.kind==='fridge').map(CounterCut.footprint));c.beginPath();for(const e of shape.edges){c.moveTo(ox+(e.a.x-x0)*s,oy+(e.a.y-y0)*s);c.lineTo(ox+(e.b.x-x0)*s,oy+(e.b.y-y0)*s);}c.strokeStyle='#77d9b8';c.stroke();});
   for(const [items,color] of [[G.fixtures||[],'#71879a'],[plan.fixtures,'#a6f5d6']])for(const f of items){if(CounterCut.inside(f,ctx.poly))Fixtures.symbol(c,f,ox+(f.x-x0)*s,oy+(f.y-y0)*s,s,color);}
   $('furnitureResult').textContent='Alternatif '+(index+1)+' / '+plans.length+' · '+plan.fixtures.length+' ürün'+(plan.counters.length?' + tezgâh':'');$('furnitureMissing').textContent=plan.missing.length?'Yerleştirilemeyenler: '+plan.missing.join(', ')+'. Bu alternatif yalnız görünen ürünleri ekler.':'Seçili gruptaki ürünler yerleşti. Gri: mevcut · Yeşil: öneri · Turuncu: kapı önü.';$('furnitureApply').disabled=false;$('furnitureNext').disabled=plans.length<2;
 }
 $('furnitureNext').onclick=()=>{index=(index+1)%plans.length;render();};
 $('furnitureApply').onclick=()=>{const p=plans[index];if(!p)return;if(Studio.snapshot()!==baseline){clear();$('furnitureResult').textContent='Plan değişti; güncel çizim için yeniden öneri oluşturun.';return;}if(Studio.edit(()=>{G.fixtures.push(...p.fixtures.map(f=>({...f,id:'fixture-'+crypto.randomUUID()})));G.counters.push(...p.counters.map(c=>({...c,id:'counter-'+crypto.randomUUID()})));})){auto.close();Studio.toast('Tefriş eklendi. Ctrl+Z tüm yerleşimi tek adımda geri alır.');}};
 const sidebar=updateSidebar;window.updateSidebar=function(){sidebar();if(G.seciliTip==='fixture'&&G.secili){const f=G.secili,b=document.createElement('button');b.className='sib';b.id='furnitureLock';b.textContent=f.locked?'🔒 Yer kilidini aç':'Yerini kilitle';b.onclick=()=>Studio.edit(()=>f.locked=!f.locked);$('sbSelIc').append(b);}};
 const roomOpen=window.openOdaModal;window.openOdaModal=function(room){roomOpen(room);let b=$('roomAutoFurniture');if(!b){b=document.createElement('button');b.id='roomAutoFurniture';b.className='sib';$('mbgOda').querySelector('.modal').append(b);}b.textContent='Bu odaya otomatik tefriş öner';b.disabled=['banyo','ebanyo','wc'].includes(room.tip);b.onclick=()=>{$('mbgOda').classList.remove('open');openAuto(room);};};
 window.FurnitureUI={openAuto,cancel:()=>{auto.close();menu.close();clear();}};
})();
