(function(){
 'use strict';
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const dlg=document.createElement('dialog');dlg.id='loadingDialog';dlg.style.cssText='margin:auto;box-sizing:border-box;width:1200px;max-width:94vw;max-height:90vh;overflow:auto;background:#152131;color:#deebf5;border:1px solid #40576b;border-radius:12px;padding:24px';
 dlg.innerHTML='<h2>Malzeme yükleme listesi <small>· Taslak</small></h2><p>Çizim adedi parçaları, sevk miktarı stok panoları gösterir. Net kesimi bilinen dolu parçalar aynı kalınlık ve yükseklikteki1250mm stoklara sığdırılır. Kesim/artık ayrıntısı listede ve Excel’dedir. Testere payı henüz tanımlanmadı. Makasın H’ye oturduğu uç bağlantısı kulaklıdır; üzerinden geçmesi yeterli değildir. Dış H dübelli, iç H dübelsizdir. H ve 10’luk/6’lık köşe direği adetleri otomatik hesaplanır. Köşe direği Excel ölçüsü 98×98 veya 58×58 ve bina yüksekliğidir. Çektirme U boyu bina yüksekliğinden60mm kısa; ölçü başına her başlayan5adede1yedek eklenir. Diğer profil/net boy, stok kesimi ve sipariş ölçüleri kontrol bekliyor. Bu liste imalat veya sevkiyat onayı değildir.</p><p id="loadSummary"></p><p>Çatı, tavan, tesisat, elektrik ve sarf grupları bu sürümde otomatik hesaplanmaz; gerekçeli manuel ek yapılabilir.</p><div style="display:flex;gap:12px;flex-wrap:wrap"><input id="loadSearch" placeholder="Malzeme / ölçü ara"><select id="loadGroup"><option value="">Tüm gruplar</option><option>Panel</option><option>Metal</option><option>Kapı / PVC</option><option>Manuel</option></select><select id="loadStatus"><option value="">Tüm durumlar</option><option>Kural bekliyor</option><option>Otomatik H adedi</option><option>Otomatik köşe direği</option><option>Otomatik U + yedek</option><option>Otomatik stok pano</option><option>Manuel doğrulandı</option><option>Çizim değişti</option><option>Manuel ek</option></select><button id="loadRefresh">Yeniden hesapla</button><button id="loadAdd">Manuel malzeme ekle</button><button id="loadExcel">Excel indir (.xlsx)</button><label><input type="checkbox" id="loadHLabels"> Planda H etiketleri (K: kulaklı · KS: kulaksız · D: dübelli · DS: dübelsiz)</label><button id="loadCsv">Tüm taslağı indir (CSV)</button><button id="loadClose">Kapat</button></div><p id="loadAlert" role="status"></p><div style="overflow:auto;max-height:42vh"><table style="width:100%;border-collapse:collapse" id="loadTable"></table></div><section id="loadEditor"></section><details id="loadOrphans" hidden><summary>Çizimde karşılığı kalmayan düzeltmeler</summary><div id="loadOrphanRows"></div></details><details><summary>Tuna Excel ile karşılaştır · referans, güncel projenin hedef miktarı değildir</summary><p id="loadRefTitle"></p><table style="width:100%" id="loadRefTable"></table></details>';
 document.body.append(dlg);const $=id=>document.getElementById(id);let current=[],selected=null;
 const style=document.createElement('style');style.textContent='#loadingDialog h2{font-size:23px;margin:0 0 14px}#loadingDialog h2 small{color:#e4bc75}#loadingDialog p{font-size:13px;line-height:1.6;margin:10px 0 16px}#loadingDialog details{margin-top:20px}#loadingDialog summary{cursor:pointer;padding:10px 0;color:#7dd9c1}#loadingDialog th{position:sticky;top:0;background:#1c3043}#loadSummary{color:#7dd9c1;font-weight:600}#loadAlert{color:#e4bc75}#loadingDialog::backdrop{background:#0008}#loadingDialog th,#loadingDialog td{padding:9px;border-bottom:1px solid #304357;text-align:left;font-size:13px}#loadingDialog input,#loadingDialog select,#loadingDialog textarea,#loadingDialog button{background:#0e1927;color:#deebf5;border:1px solid #496178;border-radius:5px;padding:8px}#loadingDialog button{cursor:pointer}#loadEditor{margin-top:18px}#loadEditor form{display:flex;gap:12px;flex-wrap:wrap;align-items:end}#loadEditor label{display:flex;flex-direction:column;gap:5px}#loadEditor textarea{width:300px}';document.head.append(style);
 const button=document.createElement('button');button.id='loadingOpen';button.className='tb';button.textContent='Yükleme listesi';button.onclick=open;document.querySelector('.header-actions').append(button);
 function items(){
  const out=[],height=+$('katYuk').value,source=(id,segIds,point,extra={})=>({id,segIds,point,...extra});
  if(isPref()){const A=pfAnaliz(),M=makasAnaliz(),components=_bilesenler();for(const r of A.runs)for(const p of r.slots){const stockWidth=LoadingCore.stockWidth(p.w,Modular.cutMm(p.w)),cut=stockWidth?.cutMm??null,name=p.acik==='kapi'?'Kapılı panel':p.acik==='pencere'?'Pencereli panel':p.tip==='ozel'?'Özel dolu panel':p.tip==='yarim'?'Yarım dolu panel':'Dolu panel';out.push({group:'Panel',name,size:`${p.k*10} × ${cut??'?'} × ${height*10} mm · yerleşim ${fmtCm(p.w)} cm`+(p.el?` · açıklık ${p.el.en}/${p.el.yuk}`:''),warning:cut==null?'Net kesim katalogda tanımsız.':'Yerleştirilen parça sayısıdır. Stok pano ve kesim planı doğrulanmalı.',source:source('panel:'+r.owner.id+':'+p.a+':'+p.b,r.items.filter(it=>it.off<p.b&&it.off+it.L>p.a).map(it=>it.seg.id),{x:r.ax+r.ux*(p.a+p.b)/2,y:r.ay+r.uy*(p.a+p.b)/2},{a:p.a,b:p.b,ux:r.ux,uy:r.uy,panelLabel:p.no||'',cutBasis:stockWidth?.basis||null,stockRule:!p.acik&&cut!=null&&cut>0&&cut<=1250?{rule:'solid-stock1250-ffd-v1',cutMm:cut,thicknessMm:p.k*10,heightMm:height*10}:null,referenceId:!p.acik&&cut!=null&&cut>0&&cut<=1250&&height===250?(p.k===10?'tuna-9':p.k===6?'tuna-10':''):'',opening:p.el?{id:p.el.id,en:p.el.en,yuk:p.el.yuk,t:p.el.t}:null})});}
   for(const b of A.bag){const uRule=b.tip==='U'?LoadingCore.uProduct(b.k,height):null;const cornerRule=b.tip==='kose'?LoadingCore.cornerProduct(b.k,height):null;const n=b.nid?getNode(b.nid):{x:b.run.ax+b.run.ux*b.pos,y:b.run.ay+b.run.uy*b.pos},segs=b.nid?G.segs.filter(s=>s.n1===b.nid||s.n2===b.nid).map(s=>s.id):b.run.items.map(it=>it.seg.id);const point={x:n.x,y:n.y},localSegs=segs.map(getSeg).filter(s=>{if(!s||s.tip==='veranda')return false;const a=getNode(s.n1),b=getNode(s.n2);return point.x>=Math.min(a.x,b.x)-.6&&point.x<=Math.max(a.x,b.x)+.6&&point.y>=Math.min(a.y,b.y)-.6&&point.y<=Math.max(a.y,b.y)+.6;}),exterior=localSegs.some(s=>s.dis),hRule=['H','H3','X'].includes(b.tip)?LoadingCore.classifyH(point,(M?.makaslar||[]).filter(m=>m.zoneId||!m.nodeId||components[m.nodeId]===components[localSegs[0]?.n1]).map(m=>({...m,axis:m.axis||(M.yatay?'x':'y')})),exterior):null;out.push({group:'Metal',name:({H:'H',H3:'Üçlü H',X:'Dörtlü birleşim',U:'Çektirme U',kose:'Köşe direği'})[b.tip]||b.tip,size:uRule?uRule.size:cornerRule?cornerRule.size:`Duvar ${b.k} cm · yükseklik ${height} cm`+(hRule?` · ${hRule.label}`:''),warning:uRule?'Çektirme U: 6’lıkta60mm,10’lukta100mm; boy bina yüksekliği−60mm. Her başlayan5adede1yedek, her ölçü ayrı hesaplanır.':cornerRule?`Çizimde ${cornerRule.nominalCm}’lık köşe direği; Excel kesiti ${cornerRule.sideMm}×${cornerRule.sideMm} mm, boy bina yüksekliği.`:hRule&&hRule.ear!==null?'Onaylı kural: gerçek uç mesnet H kulaklı; makasın arada üzerinden geçmesi yeterli değil. Dış H dübelli, iç H dübelsiz. Adet otomatik hesaplanır. Profil kesiti ve net boy ayrıca doğrulanmalı.':'Profil kesiti, kulak/dübel ve net boy reçetesi doğrulanmalı.',source:source('joint:'+(b.nid||b.run.owner.id+':'+b.pos)+':'+b.tip,segs,{x:n.x,y:n.y},{roofDirection:G.catiYon,exterior,hRule,cornerRule,uRule,referenceId:uRule?uRule.referenceId:cornerRule?cornerRule.referenceId:height===250&&hRule&&hRule.ear!==null?(({H:{"10":hRule.ear?"tuna-23":"tuna-24","6":!hRule.ear?"tuna-25":""},H3:{"10/6":hRule.ear?"tuna-26":"tuna-27","6/6":!hRule.ear?"tuna-28":""}})[b.tip]?.[b.k]||''):''})});}
   for(const n of G.nodes){const attached=G.segs.filter(s=>s.n1===n.id||s.n2===n.id);if(attached.length&&attached.every(s=>s.tip==='veranda'))out.push({group:'Metal',name:'Veranda serbest direği',size:'Kesit / boy üretim kontrolü gerekli',warning:'Çizim sembolü satın alma kesiti ve boyunu doğrulamaz.',source:source('veranda:'+n.id,attached.map(s=>s.id),{x:n.x,y:n.y})});}
  }
  for(const e of G.elemanlar){const s=getSeg(e.segId),a=getNode(s.n1),b=getNode(s.n2);out.push({group:'Kapı / PVC',name:e.tip_==='pencere'?'PVC pencere':s.dis?'Dış kapı':'İç kapı',size:`Açıklık ${e.en}/${e.yuk} cm`,warning:'Sipariş/kasa ölçüsü açıklık ölçüsünden ayrı doğrulanmalı.',source:source(e.id,[s.id],{x:a.x+(b.x-a.x)*e.t,y:a.y+(b.y-a.y)*e.t},{type:e.kapiTip||'',hinge:e.mentese||'',side:e.yan||0})});}
  return out;
 }
 function calculate(){return LoadingCore.build(items(),G.loading);}
 function commit(change){const cfg=LoadingCore.validate(G.loading);change(cfg);LoadingCore.validate(cfg);if(!Studio.edit(()=>{G.loading=cfg;}))throw Error('Yükleme değişikliği kaydedilemedi.');render();}
 function render(){const report=calculate();current=report.rows;const search=$('loadSearch').value.toLocaleLowerCase('tr'),group=$('loadGroup').value,status=$('loadStatus').value,filtered=current.filter(r=>(!group||r.group===group)&&(!status||r.status===status)&&(r.name+' '+r.size).toLocaleLowerCase('tr').includes(search));
  $('loadHLabels').checked=!!G.loading?.showLabels;
  $('loadSummary').textContent=`${Studio.state().projectName} · ${current.filter(r=>r.group==='Panel').reduce((n,r)=>n+r.calculated,0)} panel yuvası · ${current.length} malzeme satırı · ${current.filter(r=>r.qty===null).length} satır kontrol bekliyor`;
  $('loadAlert').textContent=(!isPref()?'Hafif çelikte panel/metal hesabı henüz kapsam dışı. ':'')+(report.orphan.length?`${report.orphan.length} eski düzeltmenin çizimde karşılığı kalmadı; sevk taslağına dahil edilmedi. `:'')+'Bu ayarlar JSON proje kaydıyla taşınır. Bilgisayar değiştirmeden önce Kaydet kullanın.';
  $('loadTable').innerHTML='<thead><tr><th>Grup / malzeme</th><th>Ölçü</th><th>Çizim</th><th>Sevk taslağı</th><th>Durum</th><th>İşlem</th></tr></thead><tbody>'+filtered.map(r=>'<tr><td>'+esc(r.group)+'<br><b>'+esc(r.name)+'</b></td><td>'+esc(r.size)+(r.cutting?'<details><summary>Kesim / artık</summary>'+esc(r.cutting)+'</details>':'')+'</td><td>'+esc(r.calculated??'—')+'</td><td>'+esc(r.qty??'—')+' '+esc(r.unit)+(r.spare?'<br><small>Otomatik: '+r.calculated+' + '+r.spare+' yedek</small>':'')+'</td><td>'+esc(r.status)+'</td><td><button data-edit="'+esc(r.key)+'">Düzenle</button> '+(r.sources.length?'<button data-show="'+esc(r.key)+'">Planda göster</button>':'')+'</td></tr>').join('')+'</tbody>';
  $('loadRefTitle').textContent=LoadingReference.file+' · '+LoadingReference.sheet+' · Panel grubu: 47 ürün. 49 geometrik yuva ile farkı henüz açıklanmadı.';
  $('loadRefTable').innerHTML='<tr><th>Excel satırı</th><th>Malzeme / ölçü</th><th>Excel adet</th><th>Eşlenen taslak</th><th>Fark</th></tr>'+LoadingReference.rows.map(ref=>{const links=current.filter(r=>r.referenceId===ref.id),pending=links.some(r=>r.qty===null),qty=links.reduce((n,r)=>n+(r.qty||0),0);return '<tr><td>'+ref.row+'</td><td>'+esc(ref.name)+'<br>'+esc(ref.size)+'</td><td>'+ref.qty+'</td><td>'+(pending?'Kontrol gerekli':links.length?qty:'Eşleme yok')+'</td><td>'+(!pending&&links.length?qty-ref.qty:'—')+'</td></tr>';}).join('');
  $('loadOrphans').hidden=!report.orphan.length;
  $('loadOrphanRows').innerHTML=report.orphan.map(a=>'<p>'+esc(a.key)+' · '+a.qty+' adet · '+esc(a.reason)+' <button data-orphan="'+esc(a.key)+'">Eski düzeltmeyi kaldır</button></p>').join('');
  $('loadEditor').replaceChildren();selected=null;
 }
 function editor(row){selected=row;const manual=!row||row.group==='Manuel';$('loadEditor').innerHTML='<h3>'+esc(row?.name||'Manuel malzeme')+'</h3><p>'+esc(row?.warning||'Manuel miktar çizimden hesaplanmaz; gerekçesiyle kaydedilir.')+'</p><form id="loadForm">'+(manual?'<label>Malzeme<input id="lmName" required maxlength="160" value="'+esc(row?.name||'')+'"></label><label>Ölçü<input id="lmSize" maxlength="160" value="'+esc(row?.size||'')+'"></label><label>Birim<select id="lmUnit">'+['adet','m','m²','kg','takım','kutu'].map(u=>'<option '+(row?.unit===u?'selected':'')+'>'+u+'</option>').join('')+'</select></label>':'<label>Tuna referans satırı (isteğe bağlı)<select id="lmRef"><option value="">Eşleme yok</option>'+LoadingReference.rows.filter(r=>r.group===row.group).map(r=>'<option value="'+r.id+'" '+(row.referenceId===r.id?'selected':'')+'>'+esc(r.row+' · '+r.name+' · '+r.size)+'</option>').join('')+'</select></label>')+'<label>Sevk taslağı miktarı<input id="lmQty" type="number" min="0" max="1000000" step="any" required value="'+esc(row?.qty??row?.calculated??1)+'"></label><label>Gerekçe / üretim notu<textarea id="lmReason" required maxlength="500">'+esc(row?.reason||'')+'</textarea></label><button type="submit">Kaydet</button>'+(row?'<button id="lmReset" type="button">'+(manual?'Manuel satırı sil':'Düzeltmeyi kaldır')+'</button>':'')+'</form>';
  $('loadForm').onsubmit=e=>{e.preventDefault();try{const qty=Number($('lmQty').value),reason=$('lmReason').value.trim();commit(c=>{if(manual){const a={id:row?.id||'manual-'+crypto.randomUUID(),name:$('lmName').value.trim(),size:$('lmSize').value.trim(),unit:$('lmUnit').value,qty,reason};c.manual=c.manual.filter(x=>x.id!==a.id);c.manual.push(a);}else{c.adjustments=c.adjustments.filter(x=>x.key!==row.key);c.adjustments.push({key:row.key,basis:row.basis,qty,reason,referenceId:$('lmRef').value});}});}catch(err){$('loadAlert').textContent=err.message;}};
  if(row)$('lmReset').onclick=()=>commit(c=>{if(manual)c.manual=c.manual.filter(a=>a.id!==row.id);else c.adjustments=c.adjustments.filter(a=>a.key!==row.key);});
 }
 $('loadTable').onclick=e=>{const key=e.target.dataset.edit||e.target.dataset.show;if(!key)return;const row=current.find(r=>r.key===key);if(!row)return;if(e.target.dataset.edit)editor(row);else{dlg.close();G.secili=null;G.seciliTip='seg';G.selSegs=[...new Set(row.sources.flatMap(s=>s.segIds))];const center=row.sources.reduce((p,s)=>({x:p.x+s.point.x/row.sources.length,y:p.y+s.point.y/row.sources.length}),{x:0,y:0});G.pan={x:cv.clientWidth/2-center.x*sc(),y:cv.clientHeight/2-center.y*sc()};updateSidebar();draw();Studio.toast('Kaynak duvarlar seçildi: '+row.sources.map(s=>s.id).join(', '));}};
 $('loadOrphanRows').onclick=e=>{if(e.target.dataset.orphan)commit(c=>{c.adjustments=c.adjustments.filter(a=>a.key!==e.target.dataset.orphan);});};
 const priorPanels=window.drawPanels;window.drawPanels=function(){priorPanels();if(!G.loading?.showLabels||!isPref())return;ctx.save();ctx.font='bold 10px Arial';ctx.textAlign='left';ctx.textBaseline='bottom';for(const i of items().filter(i=>i.source.hRule)){const h=i.source.hRule,c=toCv(i.source.point.x,i.source.point.y),label=(i.name==='H'?'H':i.name==='Üçlü H'?'3H':'4H')+' '+(h.ear===null?'?':h.ear?'K':'KS')+' '+(h.dowel?'D':'DS');ctx.fillStyle='#10202b';ctx.fillRect(c.x+7,c.y-18,ctx.measureText(label).width+6,14);ctx.fillStyle='#7de1c2';ctx.fillText(label,c.x+10,c.y-5);}ctx.restore();};
 $('loadHLabels').onchange=()=>{const v=$('loadHLabels').checked;commit(c=>{c.showLabels=v;});};
 function open(){try{render();dlg.showModal();}catch(e){Studio.toast(e.message,true);}}
 for(const id of ['loadSearch','loadGroup','loadStatus'])$(id).oninput=render;$('loadRefresh').onclick=render;$('loadAdd').onclick=()=>editor(null);$('loadClose').onclick=()=>dlg.close();
 $('loadCsv').onclick=()=>{const report=calculate(),data=LoadingCore.csv(report.rows,{project:Studio.state().projectName,version:'5.9.36',date:new Date().toLocaleString('tr-TR'),orphan:report.orphan.length}),url=URL.createObjectURL(new Blob([data],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='yukleme-taslak-'+new Date().toISOString().replace(/[:.]/g,'-')+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);};
 $('loadExcel').onclick=()=>{const r=calculate(),url=URL.createObjectURL(new Blob([LoadingXlsx.create(r.rows,{project:Studio.state().projectName,version:'5.9.36',date:new Date().toLocaleString('tr-TR')})],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})),a=document.createElement('a');a.href=url;a.download='yukleme-listesi.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);};
 window.LoadingList={open,calculate,items};
})();
