/* Small dependency-free OOXML export; all user strings are inline text, never formulas. */
(function(root){
 const enc=new TextEncoder(),xml=s=>String(s??'').replace(/[\x00-\x08\x0b\x0c\x0e-\x1f]/g,'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
 function zip(files){const chunks=[],central=[];let offset=0;const header=n=>new Uint8Array(n),set=(a,p,n,size)=>{const d=new DataView(a.buffer);size===2?d.setUint16(p,n,true):d.setUint32(p,n,true);};for(const [name,text] of Object.entries(files)){const data=enc.encode(text),nm=enc.encode(name);let crc=0xffffffff;for(const byte of data){crc^=byte;for(let j=0;j<8;j++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}crc=(crc^0xffffffff)>>>0;const h=header(30);set(h,0,0x04034b50,4);set(h,4,20,2);set(h,14,crc,4);set(h,18,data.length,4);set(h,22,data.length,4);set(h,26,nm.length,2);chunks.push(h,nm,data);const c=header(46);set(c,0,0x02014b50,4);set(c,4,20,2);set(c,6,20,2);set(c,16,crc,4);set(c,20,data.length,4);set(c,24,data.length,4);set(c,28,nm.length,2);set(c,42,offset,4);central.push(c,nm);offset+=30+nm.length+data.length;}const size=central.reduce((n,a)=>n+a.length,0),end=header(22);set(end,0,0x06054b50,4);set(end,8,Object.keys(files).length,2);set(end,10,Object.keys(files).length,2);set(end,12,size,4);set(end,16,offset,4);const all=[...chunks,...central,end],out=new Uint8Array(offset+size+22);let pos=0;for(const a of all){out.set(a,pos);pos+=a.length;}return out;}
 function create(rows,meta){const table=[['Yükleme listesi — taslak'],['Proje',meta.project,'Sürüm',meta.version,'Tarih',meta.date],['H: K=kulaklı, KS=kulaksız, D=dübelli, DS=dübelsiz. Profil/net boy kontrolü ayrıca gerekir.'],['Grup','Malzeme','Ölçü / sınıf','Birim','Çizim adedi','Toplam sevk (yedek dahil)','Durum','Gerekçe','Excel referansı','Kaynak kimlikler','Yedek','Kesim dağılımı (mm)','Artık toplamı (mm)','Adet','Yedek açıklaması','Net boy (mm)','Kesim payı (mm)','Sevk boyu (mm)'],...rows.map(r=>[r.group,r.name,r.size,r.unit,r.calculated,r.qty,r.status,r.reason,r.referenceId,r.sources.map(s=>s.id).join(', '),LoadingCore.shipment(r).spare,r.cutting||'',r.leftoverMm??'',LoadingCore.shipment(r).base,LoadingCore.shipment(r).label,r.netMm??'',r.cutAllowanceMm??'',r.shipLengthMm??''])];
 const sheet='<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="4" topLeftCell="A5" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols><col min="1" max="2" width="24" customWidth="1"/><col min="3" max="3" width="70" customWidth="1"/><col min="4" max="6" width="16" customWidth="1"/><col min="7" max="18" width="35" customWidth="1"/></cols><sheetData>'+table.map((r,i)=>'<row r="'+(i+1)+'">'+r.map((v,j)=>{const ref=String.fromCharCode(65+j)+(i+1),style=i===0||i===3?1:0;return typeof v==='number'?'<c r="'+ref+'" s="'+style+'"><v>'+v+'</v></c>':'<c r="'+ref+'" s="'+style+'" t="inlineStr"><is><t xml:space="preserve">'+xml(v)+'</t></is></c>';}).join('')+'</row>').join('')+'</sheetData><autoFilter ref="A4:R'+table.length+'"/></worksheet>';
 return zip({'[Content_Types].xml':'<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>',
 '_rels/.rels':'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>',
 'xl/workbook.xml':'<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Yükleme listesi" sheetId="1" r:id="rId1"/></sheets></workbook>',
 'xl/_rels/workbook.xml.rels':'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>',
 'xl/styles.xml':'<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><sz val="11"/><name val="Calibri"/></font></fonts><fills count="2"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf/></cellStyleXfs><cellXfs count="2"><xf fontId="0" fillId="0" borderId="0" xfId="0"/><xf fontId="1" fillId="0" borderId="0" xfId="0" applyFont="1"/></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>',
 'xl/worksheets/sheet1.xml':sheet});
 }
 root.LoadingXlsx={create};
})(globalThis);
