/* Quick panel actions reuse the validated manufacturing transactions. */
(()=>{
 const button=document.createElement('button');button.id='panelQuickToggle';button.className='t';button.textContent='Panel düzenle';button.title='Sol tık: böl / birleştir · sürükle: komşuyla değiştir';document.getElementById('selectionMode').after(button);
 let enabled=false,drag=null;const menu=document.createElement('div');menu.id='panelQuickMenu';menu.hidden=true;menu.style.cssText='position:fixed;z-index:5000;background:#182331;color:#eef4fa;border:1px solid #69d6b2;border-radius:8px;padding:12px;max-width:300px;box-shadow:0 8px 30px #0008';document.body.append(menu);
 const hint=document.createElement('div');hint.hidden=true;hint.style.cssText='position:fixed;z-index:5001;background:#182331;color:#69d6b2;padding:8px;border:1px solid #69d6b2;pointer-events:none';document.body.append(hint);
 function close(){menu.hidden=true;}
 button.onclick=()=>{enabled=!enabled;button.classList.toggle('active',enabled);button.setAttribute('aria-pressed',String(enabled));close();if(enabled){setTool('sec');G.selectionMode='panel';updateSidebar();draw();Studio.toast('Panel: sol tık menü · komşuya sürükle yer değiştir. Makas mesnetleri korunur.');}};
 function hit(e){const b=cv.getBoundingClientRect();return hitTestAll(e.clientX-b.left,e.clientY-b.top);}
 function show(e){const c=Prefab.resolve();if(!c)return;menu.replaceChildren();const title=document.createElement('strong');title.textContent=fmtCm(c.panel.w)+' cm panel';menu.append(title);const note=document.createElement('p');note.textContent='Makas aksları sabit. Eşlenen duvarlar birlikte kontrol edilir.';menu.append(note);
 for(const [label,action,dir] of [['Aks üzerinden ikiye böl','split'],['Öncekiyle birleştir','merge',-1],['Sonrakiyle birleştir','merge',1],['← Öncekiyle değiştir','swap',-1],['Sonrakiyle değiştir →','swap',1]]){const b=document.createElement('button');b.className='sib';b.textContent=label;b.dataset.action=action;b.dataset.dir=dir||0;b.style.cssText='display:block;width:100%;margin:5px 0';b.disabled=!!dir&&!c.run.slots[c.index+dir];b.onclick=()=>{close();Prefab.quick(action,dir);};menu.append(b);}
 const b=document.createElement('button');b.textContent='Kapat';b.className='sib';b.onclick=close;menu.append(b);menu.hidden=false;menu.style.left=Math.max(8,Math.min(e.clientX+12,innerWidth-menu.offsetWidth-8))+'px';menu.style.top=Math.max(8,Math.min(e.clientY+12,innerHeight-menu.offsetHeight-8))+'px';}
 window.addEventListener('mousedown',e=>{if(!menu.contains(e.target))close();if(!enabled||e.target!==cv||e.button!==0||!isPref()||G.tool!=='sec'||e.ctrlKey||e.shiftKey||e.metaKey)return;const h=hit(e);if(h?.tip!=='panel')return;const c=Prefab.resolve(h.obj);if(!c)return;e.preventDefault();e.stopImmediatePropagation();Prefab.select(c.run.owner.id,c.index);drag={ref:h.obj,index:c.index,owner:c.run.owner.id,x:e.clientX,y:e.clientY,moved:false};},true);
 window.addEventListener('mousemove',e=>{if(!drag)return;e.preventDefault();e.stopImmediatePropagation();if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>6)drag.moved=true;if(!drag.moved)return;const h=e.target===cv?hit(e):null,c=h?.tip==='panel'?Prefab.resolve(h.obj):null;hint.hidden=false;hint.textContent=c&&c.run.owner.id===drag.owner&&Math.abs(c.index-drag.index)===1?'Bırak: komşu panelleri değiştir':'Aynı duvardaki komşu panelin üzerine bırakın';hint.style.left=Math.min(e.clientX+12,innerWidth-310)+'px';hint.style.top=(e.clientY+15)+'px';},true);
 window.addEventListener('mouseup',e=>{if(!drag)return;const d=drag;drag=null;hint.hidden=true;e.preventDefault();e.stopImmediatePropagation();if(!d.moved){show(e);return;}const h=e.target===cv?hit(e):null,c=h?.tip==='panel'?Prefab.resolve(h.obj):null;if(!c||c.run.owner.id!==d.owner||Math.abs(c.index-d.index)!==1){Studio.toast('Yer değiştirmek için aynı duvardaki komşu paneli seçin.',true);return;}Prefab.select(d.owner,d.index);Prefab.quick('swap',c.index-d.index);},true);
 window.addEventListener('keydown',e=>{if(e.key==='Escape'){close();drag=null;hint.hidden=true;}} ,true);window.addEventListener('blur',()=>{drag=null;hint.hidden=true;close();});
})();
