/* Plan-only export. No cloud dependency and no changes to the saved model. */
(function(){
 'use strict';
 const $=id=>document.getElementById(id),PX=96/25.4,PAPERS={A4:[210,297],A3:[297,420],A2:[420,594],A1:[594,841],A0:[841,1189]};let format='pdf';
 const dialog=document.createElement('dialog');dialog.id='planExportDialog';dialog.style.cssText='background:#192334;color:#d6e6ef;border:1px solid #40566b;border-radius:12px;padding:24px;width:560px;max-width:90vw;max-height:90vh;overflow:auto';
 dialog.innerHTML='<form><h3 id="exportTitle">Plan çıktısı</h3><div id="exportPdfOptions" style="display:flex;gap:12px"><label>Kâğıt<select id="exportPaper"><option>A4</option><option selected>A3</option><option>A2</option><option>A1</option><option>A0</option></select></label><label>Yön<select id="exportOrientation"><option value="portrait" selected>Dikey</option><option value="landscape">Yatay</option></select></label><label>Ölçek<select id="exportScale"><option value="20">1:20</option><option value="50" selected>1:50</option><option value="100">1:100</option><option value="200">1:200</option></select></label></div><p id="exportDescription"></p><p id="exportStatus" role="status"></p><img id="exportPreview" alt="PDF sayfa önizlemesi" style="width:100%;max-height:310px;object-fit:contain;background:#fff"><p style="font-size:12px">Seçili görünüm filtreleri kullanılır. H, U ve köşe bağlantıları korunur. Kat planı çıktısıdır; 3B model veya imalat onayı değildir.</p><button class="sib" id="exportSubmit" type="submit">İndir</button><button class="sib" id="exportCancel" type="button">Vazgeç</button></form>';
 document.body.append(dialog);dialog.style.width='960px';dialog.style.margin='auto';
 $('exportPdfOptions').insertAdjacentHTML('afterend','<div id="sheetOptions"><label><input id="exportAntet" type="checkbox" checked> Antetli çıktı</label><details id="sheetFields"><summary>Logo, müşteri ve proje bilgileri</summary><div id="sheetInputs" class="sheet-inputs"></div><label>Logo seç (PNG / JPG / WebP)<input id="sheetLogo" type="file" accept="image/png,image/jpeg,image/webp"></label><button id="sheetLogoRemove" type="button" class="sib">Logoyu kaldır</button><p>Logo yoksa firma adı kullanılır. Bilgiler ve logo JSON proje kaydında taşınır.</p><button id="sheetSave" type="button" class="sib">Bilgileri projeye kaydet</button></details><div id="orientationPreviews" class="orientation-previews"></div></div>');
 for(const [key,label] of TitleBlock.fields){const el=document.createElement('label');el.textContent=label;const input=document.createElement('input');input.id='sheet-'+key;input.type=key==='date'?'date':'text';input.maxLength=240;el.append(input);$('sheetInputs').append(el);}
 $('exportOrientation').insertAdjacentHTML('afterbegin','<option value="auto">Otomatik öneri</option>');$('exportOrientation').value='auto';$('exportScale').insertAdjacentHTML('afterbegin','<option value="auto">En uygun ölçek</option>');$('exportScale').value='auto';
 dialog.querySelectorAll('select,input:not([type=checkbox]):not([type=file])').forEach(el=>el.style.cssText='display:block;width:100%;box-sizing:border-box;padding:8px;margin:6px 0;background:#101b29;color:#d6e6ef;border:1px solid #40566b;border-radius:5px');
 let draft={},dirty=false,refreshTimer,refreshId=0;
 exportPreview.style.maxHeight='520px';exportPreview.style.cursor='zoom-in';exportPreview.title='Büyütmek / küçültmek için tıklayın';exportPreview.onclick=()=>{const large=exportPreview.style.maxHeight==='none';exportPreview.style.maxHeight=large?'520px':'none';};
 for(const [type,label] of [['pdf','PDF çıktı'],['dxf','DXF çıktı']]){const b=document.createElement('button');b.id='export-'+type;b.className='tb';b.textContent=label;b.onclick=()=>open(type);document.querySelector('.header-actions').append(b);}
 function render(target,s,pan={x:0,y:0}){
  const save={zoom:G.zoom,pan:G.pan,secili:G.secili,seciliTip:G.seciliTip,selSegs:G.selSegs,selPanels:G.selPanels,wallDrag:G.wallDrag,lblDrag:G.lblDrag,drawing:G.drawing,snapPt:G.snapPt},old={ctx,TH,DIM};
  try{Object.assign(G,{zoom:s/G.scale,pan,secili:null,seciliTip:null,selSegs:[],selPanels:[],wallDrag:null,lblDrag:null,drawing:false,snapPt:null});ctx=target;TH=TH_PAPER;DIM=DIM_PAPER;
   for(const [name,fn] of [['ODA',drawRooms],['MAKAS',drawMakas],['DUVAR',drawSegs],['PANEL_BAGLANTI',drawPanels],['KAPLAMA',drawAlciGorsel],['DONATI_METIN',drawElemanlar],['OLCU',drawDims]]){target.setLayer?.(name);fn();}
  }finally{Object.assign(G,save);ctx=old.ctx;TH=old.TH;DIM=old.DIM;draw();}
 }
 function record(s=1){const r=PlanCanvasRecorder();render(r,s);if(!Number.isFinite(r.bounds.minX))throw Error('Önce bir plan veya metin oluşturun.');return r;}
 function layout(paper,orientation,scale,antet=false,info=G.sheetInfo||{}){
  if(!PAPERS[paper]||![20,50,100,200].includes(scale))throw Error('Geçersiz kâğıt veya ölçek.');const [a,b]=PAPERS[paper],w=orientation==='landscape'?b:a,h=orientation==='landscape'?a:b,s=10*PX/scale;
  const r=record(s),B=r.bounds,width=(B.maxX-B.minX)/PX,height=(B.maxY-B.minY)/PX,aw=w-24,ah=h-(antet?106:24);
  if(width>aw||height>ah)throw Error(`Plan bu sayfaya 1:${scale} ölçekte sığmıyor (${Math.ceil(width)} × ${Math.ceil(height)} mm). Daha büyük kâğıt veya 1:${scale<100?100:200} ölçek seçin.`);
  const dpi=[300,200,150].find(d=>w*h*d*d/(25.4*25.4)<=40000000);return {paper,orientation,scale,w,h,s,dpi,antet,info,bounds:B,score:Math.abs(Math.log(Math.max(1,width)/Math.max(1,height)/(aw/ah))),pan:{x:(w*PX-(B.maxX-B.minX))/2-B.minX,y:12*PX+(ah*PX-(B.maxY-B.minY))/2-B.minY}};
 }
 function pageCanvas(l,dpi=l.dpi){
  const out=document.createElement('canvas'),W=l.w*PX,H=l.h*PX;out.width=Math.ceil(l.w*dpi/25.4);out.height=Math.ceil(l.h*dpi/25.4);
  if(out.width*out.height>150000000)throw Error('Bu sayfa çözünürlüğü çok büyük. Daha küçük kâğıt seçin.');
  const c=out.getContext('2d');if(!c)throw Error('Çıktı tuvali oluşturulamadı.');c.setTransform(out.width/W,0,0,out.height/H,0,0);c.fillStyle='#fff';c.fillRect(0,0,W,H);render(c,l.s,l.pan);
  if(l.antet)TitleBlock.paint(c,l,l.info);
  return out;
 }
 function makePdf(l){const canvas=pageCanvas(l),data=atob(canvas.toDataURL('image/jpeg',.97).split(',')[1]),bytes=Uint8Array.from(data,c=>c.charCodeAt(0));return PlanExportCore.pdf(bytes,canvas.width,canvas.height,l.w,l.h);}
 function makeDxf(){const r=record(1);return PlanExportCore.dxf([...PlanExportCore.wallPieces(Studio.state()),...r.items]);}
 function download(data,ext,mime){const name=(Studio.state().projectName||'plan').replace(/[<>:"/\\|?*\x00-\x1f]/g,'_'),url=URL.createObjectURL(new Blob([data],{type:mime})),a=document.createElement('a');a.href=url;a.download=name+'.'+ext;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
 function recommend(paper,orientation='auto',scale='auto',antet=true,info={}){const candidates=[];for(const dir of orientation==='auto'?['portrait','landscape']:[orientation])for(const value of scale==='auto'?[20,50,100,200]:[+scale]){try{candidates.push(layout(paper,dir,value,antet,info));break;}catch(e){if(!/sığmıyor/.test(e.message))throw e;}}if(!candidates.length)throw Error('Plan seçili kâğıda sığmıyor. Daha büyük kâğıt veya daha küçük ölçek seçin.');return candidates.sort((a,b)=>a.scale-b.scale||a.score-b.score)[0];}
 function readFields(){for(const [key] of TitleBlock.fields)draft[key]=$('sheet-'+key).value;return structuredClone(draft);}
 function chosen(dir=$('exportOrientation').value){return recommend($('exportPaper').value,dir,$('exportScale').value,$('exportAntet').checked,readFields());}
 async function refresh(){const id=++refreshId;$('exportSubmit').disabled=true;try{if(format!=='dxf'){await TitleBlock.ready(readFields());if(id!==refreshId)return;const l=chosen();$('exportPreview').src=pageCanvas(l,72).toDataURL('image/png');$('exportPreview').hidden=false;$('exportStatus').textContent=`${l.antet?'Antetli':'Antetsiz'} · ${l.orientation==='portrait'?'Dikey':'Yatay'} · ${l.w} × ${l.h} mm · 1:${l.scale} · ${l.dpi} dpi`;$('orientationPreviews').replaceChildren();for(const dir of ['portrait','landscape']){const button=document.createElement('button');button.type='button';button.className='orientation-card';button.setAttribute('aria-pressed',String(l.orientation===dir));try{const alt=chosen(dir),image=document.createElement('img');image.src=pageCanvas(alt,40).toDataURL('image/png');image.alt=dir==='portrait'?'Dikey yerleşim':'Yatay yerleşim';button.append(image,document.createTextNode((dir==='portrait'?'Dikey':'Yatay')+' · 1:'+alt.scale+(l.orientation===dir?' · Seçili':'')));button.onclick=()=>{$('exportOrientation').value=dir;refresh();};}catch{button.textContent=(dir==='portrait'?'Dikey':'Yatay')+' · Sığmıyor';button.disabled=true;}$('orientationPreviews').append(button);}}else{record(1);$('exportPreview').hidden=true;$('exportStatus').textContent='1:1 model · 1 birim = 1 mm · Yazılı ölçüler cm olarak korunur.';}$('exportSubmit').disabled=false;}catch(e){if(id!==refreshId)return;$('exportPreview').hidden=true;$('exportStatus').textContent=e.message;$('exportSubmit').disabled=true;}}
 async function open(type){format=type;dirty=false;draft=structuredClone(G.sheetInfo||{});const defaults={company:'PREFABRİKTEN',date:new Date().toLocaleDateString('sv-SE'),title:'Kat planı',sheetNo:'A-01'};for(const [key] of TitleBlock.fields)$('sheet-'+key).value=draft[key]??defaults[key]??'';$('sheetLogo').value='';$('exportTitle').textContent=type==='dxf'?'AutoCAD için DXF çıktısı':type.toUpperCase()+' · Antet ve sayfa düzeni';$('sheetOptions').hidden=type==='dxf';$('exportPdfOptions').style.display=type==='dxf'?'none':'flex';$('exportDescription').textContent=type==='dxf'?'Düzenlenebilir 2B çizgiler/yazılar; geometri mm, ölçü etiketleri cm. Antet DXF içine eklenmez.':'Dikey ve yatay yerleşimleri karşılaştırın. Otomatik öneri, sığan en büyük standart ölçeği seçer. PDF’de %100 / Gerçek boyut kullanın. PNG’nin kâğıt ölçeği, tam seçili kâğıt boyutunda basıldığında geçerlidir.';dialog.showModal();await refresh();}
 function saveInfo(){if(!dirty)return true;const info=readFields();try{PlanProject.validate({...Studio.state(),sheetInfo:info});if(!Studio.edit(()=>{G.sheetInfo=info;}))return false;dirty=false;return true;}catch(e){Studio.toast(e.message,true);return false;}}
 dialog.querySelectorAll('select').forEach(el=>el.onchange=refresh);$('exportAntet').onchange=refresh;for(const [key] of TitleBlock.fields)$('sheet-'+key).oninput=()=>{dirty=true;clearTimeout(refreshTimer);refreshTimer=setTimeout(refresh,180);};
 $('sheetSave').onclick=()=>{if(saveInfo())Studio.toast('Antet bilgileri projeye kaydedildi. İki bilgisayar için JSON kaydınızı da alın.');};
 $('sheetLogo').onchange=async e=>{const file=e.target.files[0];if(!file)return;const active=draft;$('exportSubmit').disabled=true;try{const logo=await TitleBlock.importLogo(file);if(active!==draft||!dialog.open)return;draft.logo=logo;dirty=true;await refresh();}catch(err){$('exportStatus').textContent=err.message;}};
 $('sheetLogoRemove').onclick=()=>{delete draft.logo;dirty=true;$('sheetLogo').value='';refresh();};$('exportCancel').onclick=()=>{refreshId++;dialog.close();};
 dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();$('exportSubmit').disabled=true;try{if(format==='dxf')download(makeDxf(),'dxf','application/dxf');else{await TitleBlock.ready(readFields());const l=chosen();if(format==='pdf')download(makePdf(l),'pdf','application/pdf');else{const canvas=pageCanvas(l);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw Error('PNG oluşturulamadı.');download(PlanExportCore.pngDensity(new Uint8Array(await blob.arrayBuffer()),l.dpi),'png','image/png');}saveInfo();}refreshId++;dialog.close();Studio.toast(format.toUpperCase()+' çıktısı hazırlandı.');}catch(err){$('exportStatus').textContent=err.message;Studio.toast(err.message,true);$('exportSubmit').disabled=false;}};
 window.pngIndir=()=>open('png');
 window.PlanExport={open,record,layout,pageCanvas,makePdf,makeDxf,recommend};
})();
