/* Plan-only export. No cloud dependency and no changes to the saved model. */
(function(){
 'use strict';
 const $=id=>document.getElementById(id),PX=96/25.4,PAPERS={A4:[210,297],A3:[297,420],A2:[420,594],A1:[594,841],A0:[841,1189]};let format='pdf';
 const dialog=document.createElement('dialog');dialog.id='planExportDialog';dialog.style.cssText='background:#192334;color:#d6e6ef;border:1px solid #40566b;border-radius:12px;padding:24px;width:560px;max-width:90vw;max-height:90vh;overflow:auto';
 dialog.innerHTML='<form><h3 id="exportTitle">Plan çıktısı</h3><div id="exportPdfOptions" style="display:flex;gap:12px"><label>Kâğıt<select id="exportPaper"><option>A4</option><option selected>A3</option><option>A2</option><option>A1</option><option>A0</option></select></label><label>Yön<select id="exportOrientation"><option value="portrait" selected>Dikey</option><option value="landscape">Yatay</option></select></label><label>Ölçek<select id="exportScale"><option value="20">1:20</option><option value="50" selected>1:50</option><option value="100">1:100</option><option value="200">1:200</option></select></label></div><p id="exportDescription"></p><p id="exportStatus" role="status"></p><img id="exportPreview" alt="PDF sayfa önizlemesi" style="width:100%;max-height:310px;object-fit:contain;background:#fff"><p style="font-size:12px">Seçili görünüm filtreleri kullanılır. H, U ve köşe bağlantıları korunur. Kat planı çıktısıdır; 3B model veya imalat onayı değildir.</p><button class="sib" id="exportSubmit" type="submit">İndir</button><button class="sib" id="exportCancel" type="button">Vazgeç</button></form>';
 document.body.append(dialog);$('exportDescription').insertAdjacentHTML('afterend','<div id="dxfOptions" hidden><label>DXF detay düzeyi<select id="dxfMode"><option value="simple">Sade plan</option><option value="panels">Panel detayı</option><option value="current">Ekrandaki detaylar</option></select></label><label><input type="checkbox" id="dxfHatch" checked> Banyo / veranda taramaları</label><p>Ölçüler tek CAD ölçü nesnesi; taramalar tek HATCH nesnesidir. H, U ve köşe direkleri her seçenekte korunur.</p></div>');dialog.style.width='960px';dialog.style.margin='auto';
 $('exportPdfOptions').insertAdjacentHTML('afterend','<div id="sheetOptions"><label><input id="exportAntet" type="checkbox" checked> Antetli çıktı</label><details id="sheetFields"><summary>Logo, müşteri ve proje bilgileri</summary><div id="sheetInputs" class="sheet-inputs"></div><label>Logo seç (PNG / JPG / WebP)<input id="sheetLogo" type="file" accept="image/png,image/jpeg,image/webp"></label><button id="sheetLogoRemove" type="button" class="sib">Logoyu kaldır</button><p>Logo yoksa firma adı kullanılır. Bilgiler ve logo JSON proje kaydında taşınır.</p><button id="sheetSave" type="button" class="sib">Bilgileri projeye kaydet</button></details><div id="orientationPreviews" class="orientation-previews"></div></div>');
 for(const [key,label] of TitleBlock.fields){const el=document.createElement('label');el.textContent=label;const input=document.createElement('input');input.id='sheet-'+key;input.type=key==='date'?'date':'text';input.maxLength=240;el.append(input);$('sheetInputs').append(el);}
 $('exportOrientation').insertAdjacentHTML('afterbegin','<option value="auto">Otomatik öneri</option>');$('exportOrientation').value='auto';$('exportScale').insertAdjacentHTML('afterbegin','<option value="auto">En uygun ölçek</option>');$('exportScale').value='auto';
 dialog.querySelectorAll('select,input:not([type=checkbox]):not([type=file])').forEach(el=>el.style.cssText='display:block;width:100%;box-sizing:border-box;padding:8px;margin:6px 0;background:#101b29;color:#d6e6ef;border:1px solid #40566b;border-radius:5px');
 let draft={},dirty=false,refreshTimer,refreshId=0;
 exportPreview.style.maxHeight='520px';exportPreview.style.cursor='zoom-in';exportPreview.title='Büyütmek / küçültmek için tıklayın';exportPreview.onclick=()=>{const large=exportPreview.style.maxHeight==='none';exportPreview.style.maxHeight=large?'520px':'none';};
 for(const [type,label] of [['pdf','PDF çıktı'],['dxf','DXF çıktı']]){const b=document.createElement('button');b.id='export-'+type;b.className='tb';b.textContent=label;b.onclick=()=>open(type);document.querySelector('.header-actions').append(b);}
 function render(target,s,pan={x:0,y:0},steps=null){
  const save={zoom:G.zoom,pan:G.pan,secili:G.secili,seciliTip:G.seciliTip,selSegs:G.selSegs,selPanels:G.selPanels,wallDrag:G.wallDrag,lblDrag:G.lblDrag,drawing:G.drawing,snapPt:G.snapPt},old={ctx,TH,DIM};
  try{Object.assign(G,{zoom:s/G.scale,pan,secili:null,seciliTip:null,selSegs:[],selPanels:[],wallDrag:null,lblDrag:null,drawing:false,snapPt:null});ctx=target;TH=TH_PAPER;DIM=DIM_PAPER;
   for(const [name,fn] of (steps||[['ODA',drawRooms],['MAKAS',drawMakas],['DUVAR',drawSegs],['PANEL_BAGLANTI',drawPanels],['KAPLAMA',drawAlciGorsel],['DONATI_METIN',drawElemanlar],['OLCU',drawDims]])){target.setLayer?.(name);fn();}
  }finally{Object.assign(G,save);ctx=old.ctx;TH=old.TH;DIM=old.DIM;draw();}
 }
 function record(s=1){const r=PlanCanvasRecorder();render(r,s);if(!Number.isFinite(r.bounds.minX))throw Error('Önce bir plan veya metin oluşturun.');return r;}
 function layout(paper,orientation,scale,antet=false,info=G.sheetInfo||{}){
  if(!PAPERS[paper]||![20,50,100,200].includes(scale))throw Error('Geçersiz kâğıt veya ölçek.');const [a,b]=PAPERS[paper],w=orientation==='landscape'?b:a,h=orientation==='landscape'?a:b,s=10*PX/scale;
  const r=record(s),B=r.bounds,width=(B.maxX-B.minX)/PX,height=(B.maxY-B.minY)/PX,aw=w-24,ah=h-(antet?106:24);
  if(width>aw||height>ah)throw Error(`Plan bu sayfaya 1:${scale} ölçekte sığmıyor (${Math.ceil(width)} × ${Math.ceil(height)} mm). Daha büyük kâğıt veya 1:${scale<100?100:200} ölçek seçin.`);
  const dpi=[300,200,150].find(d=>w*h*d*d/(25.4*25.4)<=40000000);return {paper,orientation,scale,w,h,s,dpi,antet,info,bounds:B,score:Math.abs(Math.log(Math.max(1,width)/Math.max(1,height)/(aw/ah))),pan:{x:(w*PX-(B.maxX-B.minX))/2-B.minX,y:12*PX+(ah*PX-(B.maxY-B.minY))/2-B.minY}};
 }
 function pageCanvas(l,dpi=l.dpi){
  const out=document.createElement('canvas'),W=l.w*PX,H=l.h*PX;out.width=Math.ceil(l.w*dpi/25.4);out.height=Math.ceil(l.h*dpi/25.4);
  if(out.width*out.height>150000000)throw Error('Bu sayfa çözünürlüğü çok büyük. Daha küçük kâğıt seçin.');
  const c=out.getContext('2d');if(!c)throw Error('Çıktı tuvali oluşturulamadı.');c.setTransform(out.width/W,0,0,out.height/H,0,0);c.fillStyle='#fff';c.fillRect(0,0,W,H);render(c,l.s,l.pan);
  if(l.antet)TitleBlock.paint(c,l,l.info);
  return out;
 }
 function makePdf(l){const canvas=pageCanvas(l),data=atob(canvas.toDataURL('image/jpeg',.97).split(',')[1]),bytes=Uint8Array.from(data,c=>c.charCodeAt(0));return PlanExportCore.pdf(bytes,canvas.width,canvas.height,l.w,l.h);}
 function dxfObjects(){
 const out=[],capture=(layer,fn)=>{const r=PlanCanvasRecorder();if(layer==='OLCU')r.nativeDimension=d=>r.items.push(CadSymbols.dimension(d));render(r,1,{x:0,y:0},[[layer,fn]]);return r.items;};let serial=0;
 function block(name,items,origin){if(!items.length)return;origin=origin||(items[0].points?.[0]||{x:items[0].x,y:items[0].y});out.push({blockName:'PS_'+name+'_'+(++serial),layer:items[0].layer,origin:{...origin},items:items.map(e=>e.points?{...e,points:e.points.map(p=>({x:p.x-origin.x,y:p.y-origin.y}))}:{...e,x:e.x-origin.x,y:e.y-origin.y})});}
 const panelOpenings=new Set();
 function openingItems(e){const save={elemanlar:G.elemanlar,fixtures:G.fixtures,counters:G.counters,annotations:G.annotations};try{Object.assign(G,{elemanlar:[e],fixtures:[],counters:[],annotations:[]});return capture('DONATI_METIN',drawElemanlar);}finally{Object.assign(G,save);}}
 if(isPref()){
  const A=pfAnaliz();for(const r of A.runs)for(const p of r.slots){const point=(t,o)=>({x:r.ax+r.ux*t-r.uy*o,y:r.ay+r.uy*t+r.ux*o});const items=[],spans=[];if(p.acik&&p.el){const e=p.el,seg=getSeg(e.segId),a=getNode(seg.n1),b=getNode(seg.n2),L=Math.hypot(b.x-a.x,b.y-a.y),ux=(b.x-a.x)/L,uy=(b.y-a.y)/L;const project=t=>(a.x+ux*t-r.ax)*r.ux+(a.y+uy*t-r.ay)*r.uy,ends=[project(e.t*L),project(e.t*L+e.en)].sort((a,b)=>a-b);spans.push([p.a,Math.max(p.a,Math.min(p.b,ends[0]))],[Math.min(p.b,Math.max(p.a,ends[1])),p.b]);items.push(...openingItems(e));panelOpenings.add(e.id);}else spans.push([p.a,p.b]);for(const [lo,hi] of spans)if(hi-lo>.001)items.push({layer:'PANEL',closed:true,points:[point(lo,p.k/2),point(hi,p.k/2),point(hi,-p.k/2),point(lo,-p.k/2)]});if(G.pnlEtiket&&p.no&&!p.acik)items.push({layer:'PANEL_NO',text:p.no,...point((p.a+p.b)/2,0),height:Math.min(7,p.k*.65),angle:Math.atan2(r.uy,r.ux),align:1,baseline:2});block('PANEL_'+String(p.no||p.tip).replace(/[^A-Za-z0-9_]/g,'_'),items,point(p.a,0));}
  for(const b of A.bag)block('BAGLANTI_'+b.tip,CadSymbols.joint(b));
  for(const e of CadSymbols.verandaEdges())block('VERANDA',[e]);
 }else{for(const e of PlanExportCore.wallPieces(Studio.state()).filter(e=>e.layer!=='VERANDA'))block('DUVAR',[e]);for(const e of CadSymbols.verandaEdges())block('VERANDA',[e]);}
 const saved={elemanlar:G.elemanlar,fixtures:G.fixtures,counters:G.counters,annotations:G.annotations};
 try{for(const key of Object.keys(saved))G[key]=[];
  for(const [key,name] of [['elemanlar','ACIKLIK'],['fixtures','TEFRIS'],['counters','TEZGAH'],['annotations','METIN']])for(const object of saved[key]||[]){if(key==='elemanlar'&&panelOpenings.has(object.id))continue;G[key]=[object];if(key==='counters')G.fixtures=saved.fixtures;const items=capture('DONATI_METIN',()=>{if(key==='counters'){for(const edge of Kitchen.effective(object).edges){ctx.beginPath();ctx.moveTo(edge.a.x,edge.a.y);ctx.lineTo(edge.b.x,edge.b.y);ctx.stroke();}}else drawElemanlar();});block(name,items);G[key]=[];G.fixtures=[];}
 }finally{Object.assign(G,saved);}
 for(const room of G.rooms){const saved=G.rooms;let labels=[];try{G.rooms=[room];labels=capture('ODA',drawRooms).filter(e=>e.text!==undefined);block('ODA',labels);}finally{G.rooms=saved;}if(['veranda','banyo','ebanyo','wc'].includes(room.tip)){const loops=CadSymbols.hatchLoops(room),points=loops[0];if(points?.length>=3)out.push({hatch:true,grid:room.tip!=='veranda',layer:'TARAMA',points,loops,holes:CadSymbols.labelIsland(labels,points)});}}
 for(const n of G.nodes){const connected=G.segs.filter(s=>s.n1===n.id||s.n2===n.id);if(connected.length&&connected.every(s=>s.tip==='veranda')){const items=[10,8].map(size=>({layer:'KOSE_DIREGI',closed:true,points:[[-1,-1],[1,-1],[1,1],[-1,1]].map(([x,y])=>({x:n.x+x*size/2,y:n.y+y*size/2}))}));block('VERANDA_DIREGI',items,n);}}
 for(const [name,fn] of [['MAKAS',drawMakas],['OLCU',drawDims],['KAPLAMA',drawAlciGorsel]]){const items=capture(name,fn);if(name==='OLCU')out.push(...items);else block(name,items);}
 return out;
}
function makeDxf(mode='current',hatch=true){const save={viewFilters:G.viewFilters,pnlEtiket:G.pnlEtiket,makasGoster:G.makasGoster,olcuModu:G.olcuModu};try{if(mode!=='current'){G.viewFilters={...G.viewFilters,rooms:true,outerDims:true,innerDims:true,chains:mode==='panels',architecturalDims:mode==='simple',openings:true};G.pnlEtiket=mode==='panels';G.makasGoster=false;G.olcuModu='panel';}return PlanExportCore.dxf(dxfObjects().filter(e=>hatch||!e.hatch));}finally{Object.assign(G,save);draw();}}

 function download(data,ext,mime){const name=(Studio.state().projectName||'plan').replace(/[<>:"/\\|?*\x00-\x1f]/g,'_'),url=URL.createObjectURL(new Blob([data],{type:mime})),a=document.createElement('a');a.href=url;a.download=name+'.'+ext;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
 function recommend(paper,orientation='auto',scale='auto',antet=true,info={}){const candidates=[];for(const dir of orientation==='auto'?['portrait','landscape']:[orientation])for(const value of scale==='auto'?[20,50,100,200]:[+scale]){try{candidates.push(layout(paper,dir,value,antet,info));break;}catch(e){if(!/sığmıyor/.test(e.message))throw e;}}if(!candidates.length)throw Error('Plan seçili kâğıda sığmıyor. Daha büyük kâğıt veya daha küçük ölçek seçin.');return candidates.sort((a,b)=>a.scale-b.scale||a.score-b.score)[0];}
 function readFields(){for(const [key] of TitleBlock.fields)draft[key]=$('sheet-'+key).value;return structuredClone(draft);}
 function chosen(dir=$('exportOrientation').value){return recommend($('exportPaper').value,dir,$('exportScale').value,$('exportAntet').checked,readFields());}
 async function refresh(){const id=++refreshId;$('exportSubmit').disabled=true;try{if(format!=='dxf'){await TitleBlock.ready(readFields());if(id!==refreshId)return;const l=chosen();$('exportPreview').src=pageCanvas(l,72).toDataURL('image/png');$('exportPreview').hidden=false;$('exportStatus').textContent=`${l.antet?'Antetli':'Antetsiz'} · ${l.orientation==='portrait'?'Dikey':'Yatay'} · ${l.w} × ${l.h} mm · 1:${l.scale} · ${l.dpi} dpi`;$('orientationPreviews').replaceChildren();for(const dir of ['portrait','landscape']){const button=document.createElement('button');button.type='button';button.className='orientation-card';button.setAttribute('aria-pressed',String(l.orientation===dir));try{const alt=chosen(dir),image=document.createElement('img');image.src=pageCanvas(alt,40).toDataURL('image/png');image.alt=dir==='portrait'?'Dikey yerleşim':'Yatay yerleşim';button.append(image,document.createTextNode((dir==='portrait'?'Dikey':'Yatay')+' · 1:'+alt.scale+(l.orientation===dir?' · Seçili':'')));button.onclick=()=>{$('exportOrientation').value=dir;refresh();};}catch{button.textContent=(dir==='portrait'?'Dikey':'Yatay')+' · Sığmıyor';button.disabled=true;}$('orientationPreviews').append(button);}}else{record(1);$('exportPreview').hidden=true;$('exportStatus').textContent='1:1 model · 1 birim = 1 mm · Yazılı ölçüler cm olarak korunur.';}$('exportSubmit').disabled=false;}catch(e){if(id!==refreshId)return;$('exportPreview').hidden=true;$('exportStatus').textContent=e.message;$('exportSubmit').disabled=true;}}
 async function open(type){format=type;$('dxfOptions').hidden=type!=='dxf';dirty=false;draft=structuredClone(G.sheetInfo||{});const defaults={company:'PREFABRİKTEN',date:new Date().toLocaleDateString('sv-SE'),title:'Kat planı',sheetNo:'A-01'};for(const [key] of TitleBlock.fields)$('sheet-'+key).value=draft[key]??defaults[key]??'';$('sheetLogo').value='';$('exportTitle').textContent=type==='dxf'?'AutoCAD için DXF çıktısı':type.toUpperCase()+' · Antet ve sayfa düzeni';$('sheetOptions').hidden=type==='dxf';$('exportPdfOptions').style.display=type==='dxf'?'none':'flex';$('exportDescription').textContent=type==='dxf'?'Ayrı seçilebilir panel, bağlantı ve tefriş blokları; geometri mm, ölçü etiketleri cm. Antet DXF içine eklenmez.':'Dikey ve yatay yerleşimleri karşılaştırın. Otomatik öneri, sığan en büyük standart ölçeği seçer. PDF’de %100 / Gerçek boyut kullanın. PNG’nin kâğıt ölçeği, tam seçili kâğıt boyutunda basıldığında geçerlidir.';dialog.showModal();await refresh();}
 function saveInfo(){if(!dirty)return true;const info=readFields();try{PlanProject.validate({...Studio.state(),sheetInfo:info});if(!Studio.edit(()=>{G.sheetInfo=info;}))return false;dirty=false;return true;}catch(e){Studio.toast(e.message,true);return false;}}
 dialog.querySelectorAll('select').forEach(el=>el.onchange=refresh);$('exportAntet').onchange=refresh;for(const [key] of TitleBlock.fields)$('sheet-'+key).oninput=()=>{dirty=true;clearTimeout(refreshTimer);refreshTimer=setTimeout(refresh,180);};
 $('sheetSave').onclick=()=>{if(saveInfo())Studio.toast('Antet bilgileri projeye kaydedildi. İki bilgisayar için JSON kaydınızı da alın.');};
 $('sheetLogo').onchange=async e=>{const file=e.target.files[0];if(!file)return;const active=draft;$('exportSubmit').disabled=true;try{const logo=await TitleBlock.importLogo(file);if(active!==draft||!dialog.open)return;draft.logo=logo;dirty=true;await refresh();}catch(err){$('exportStatus').textContent=err.message;}};
 $('sheetLogoRemove').onclick=()=>{delete draft.logo;dirty=true;$('sheetLogo').value='';refresh();};$('exportCancel').onclick=()=>{refreshId++;dialog.close();};
 dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();$('exportSubmit').disabled=true;try{if(format==='dxf')download(makeDxf($('dxfMode').value,$('dxfHatch').checked),'dxf','application/dxf');else{await TitleBlock.ready(readFields());const l=chosen();if(format==='pdf')download(makePdf(l),'pdf','application/pdf');else{const canvas=pageCanvas(l);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw Error('PNG oluşturulamadı.');download(PlanExportCore.pngDensity(new Uint8Array(await blob.arrayBuffer()),l.dpi),'png','image/png');}saveInfo();}refreshId++;dialog.close();Studio.toast(format.toUpperCase()+' çıktısı hazırlandı.');}catch(err){$('exportStatus').textContent=err.message;Studio.toast(err.message,true);$('exportSubmit').disabled=false;}};
 window.pngIndir=()=>open('png');
 window.PlanExport={open,record,layout,pageCanvas,makePdf,makeDxf,dxfObjects,recommend};
})();
