(function(){
window.ReferenceImageEnabled=true;
const panel=document.createElement('section');panel.id='referencePanel';panel.hidden=true;panel.setAttribute('aria-label','Referans görsel');panel.innerHTML=`<header><strong>Referans görsel</strong><button id="refHide" title="Gizle">×</button></header><div class="ref-tools"><button id="refImport">Görsel aç</button><button id="refMinus" aria-label="Referansı küçült">−</button><button id="refPlus" aria-label="Referansı büyüt">+</button><button id="refFit">Sığdır</button><button id="refRemove">Kaldır</button></div><div id="refViewport" tabindex="0"><img id="refImage" draggable="false" hidden><p id="refEmpty">Görsel aç veya ekran görüntüsünü Ctrl+V ile yapıştır.<br>Görseli buraya sürükleyip bırakabilirsin.</p></div><small id="refStatus">Başlıktan taşı · Köşeden boyutlandır · Tekerlekle yakınlaş</small><small>Son referans bu tarayıcıda tutulur; proje JSON’una eklenmez.</small><input id="refFile" type="file" accept="image/png,image/jpeg,image/webp,image/bmp" hidden>`;document.body.append(panel);
const $=id=>document.getElementById(id),view=$('refViewport'),img=$('refImage');let scale=1,x=0,y=0,url=null,token=0;
const button=document.createElement('button');button.className='t';button.id='referenceToggle';button.textContent='▧ Referans görsel';button.onclick=()=>{panel.hidden=!panel.hidden;if(!panel.hidden)clamp();};document.querySelector('.tool-ribbon').append(button);
function status(s){$('refStatus').textContent=s;}
function clamp(){panel.style.left=Math.max(0,Math.min(parseFloat(panel.style.left)||innerWidth-500,innerWidth-panel.offsetWidth))+'px';panel.style.top=Math.max(0,Math.min(parseFloat(panel.style.top)||170,innerHeight-panel.offsetHeight))+'px';}
function paint(){img.style.transform=`translate(${x}px,${y}px) scale(${scale})`;}
function fit(){if(!img.naturalWidth)return;scale=Math.min(view.clientWidth/img.naturalWidth,view.clientHeight/img.naturalHeight);x=(view.clientWidth-img.naturalWidth*scale)/2;y=(view.clientHeight-img.naturalHeight*scale)/2;paint();}
function zoom(f,cx=view.clientWidth/2,cy=view.clientHeight/2){const next=Math.max(.02,Math.min(12,scale*f));x=cx-(cx-x)*next/scale;y=cy-(cy-y)*next/scale;scale=next;paint();}
function db(){return new Promise((resolve,reject)=>{const q=indexedDB.open('planstudio-reference-preview',1);q.onupgradeneeded=()=>q.result.createObjectStore('images');q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error);});}
async function storage(value,read=false){const d=await db();try{return await new Promise((resolve,reject)=>{const tx=d.transaction('images',read?'readonly':'readwrite'),s=tx.objectStore('images');const q=read?s.get('last'):value?s.put(value,'last'):s.delete('last');tx.oncomplete=()=>resolve(q.result);tx.onerror=()=>reject(tx.error);});}finally{d.close();}}
async function load(file,persist=true){const mine=++token;if(!/^image\/(png|jpeg|webp|bmp)$/.test(file.type)){status('PNG, JPG, WebP veya BMP görsel seçin.');return;}if(file.size>30*1024*1024){status('Görsel en fazla 30 MB olabilir.');return;}const next=URL.createObjectURL(file),probe=new Image();try{probe.src=next;await probe.decode();if(mine!==token){URL.revokeObjectURL(next);return;}if(url)URL.revokeObjectURL(url);url=next;img.src=url;await img.decode();img.hidden=false;$('refEmpty').hidden=true;panel.hidden=false;clamp();fit();status('Sürükle: görseli kaydır · Tekerlek: yakınlaş');if(persist)try{await storage(file);}catch{status('Görsel açık; tarayıcıya kaydedilemedi.');}}catch{URL.revokeObjectURL(next);status('Görsel okunamadı. Başka bir dosya deneyin.');}}
$('refImport').onclick=()=>$('refFile').click();$('refFile').onchange=e=>{if(e.target.files[0])load(e.target.files[0]);e.target.value='';};$('refHide').onclick=()=>panel.hidden=true;$('refFit').onclick=fit;$('refPlus').onclick=()=>zoom(1.25);$('refMinus').onclick=()=>zoom(.8);$('refRemove').onclick=async()=>{++token;img.hidden=true;img.removeAttribute('src');if(url)URL.revokeObjectURL(url);url=null;$('refEmpty').hidden=false;try{await storage(null);status('Referans kaldırıldı.');}catch{status('Tarayıcı kaydı silinemedi.');}};
view.addEventListener('wheel',e=>{e.preventDefault();const r=view.getBoundingClientRect();zoom(e.deltaY<0?1.15:1/1.15,e.clientX-r.left,e.clientY-r.top);},{passive:false});
function drag(el,move){el.addEventListener('pointerdown',e=>{if(e.button!==0||e.target.closest('button'))return;e.preventDefault();el.setPointerCapture(e.pointerId);let px=e.clientX,py=e.clientY;const update=v=>{move(v.clientX-px,v.clientY-py);px=v.clientX;py=v.clientY;};const stop=()=>{el.removeEventListener('pointermove',update);el.removeEventListener('pointerup',stop);el.removeEventListener('lostpointercapture',stop);};el.addEventListener('pointermove',update);el.addEventListener('pointerup',stop);el.addEventListener('lostpointercapture',stop);});}
drag(panel.querySelector('header'),(dx,dy)=>{panel.style.left=(panel.offsetLeft+dx)+'px';panel.style.top=(panel.offsetTop+dy)+'px';clamp();});drag(view,(dx,dy)=>{x+=dx;y+=dy;paint();});
view.addEventListener('dragover',e=>e.preventDefault());view.addEventListener('drop',e=>{e.preventDefault();if(e.dataTransfer.files[0])load(e.dataTransfer.files[0]);});
window.addEventListener('paste',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||e.target.isContentEditable||document.querySelector('dialog[open],.mbg.open'))return;const item=[...(e.clipboardData?.items||[])].find(i=>i.type.startsWith('image/'));if(item){e.preventDefault();load(item.getAsFile());}else if(window.PlanClipboard){e.preventDefault();PlanClipboard.paste();}},true);
panel.addEventListener('keydown',e=>{if(!(e.ctrlKey||e.metaKey)&&e.key!=='Tab')e.stopPropagation();});new ResizeObserver(()=>{if(!panel.hidden)clamp();}).observe(panel);window.addEventListener('resize',clamp);
const initial=token;storage(null,true).then(file=>{if(file&&token===initial)load(file,false);}).catch(()=>{});
})();
