(function(){
 const $=id=>document.getElementById(id);let target=null;
 const dialog=document.createElement('dialog');dialog.id='verandaMeasureDialog';dialog.style.cssText='background:#192334;color:#d6e6ef;border:1px solid #40566b;border-radius:12px;padding:24px;width:390px';
 dialog.innerHTML='<form><h3>Veranda net ölçüsü</h3><label>Yeni net ölçü · cm<input id="verandaNet" type="number" min="1" max="100000" step="any" required></label><label>Sabit kalacak taraf<select id="verandaFixed"></select></label><p id="verandaPreview"></p><p>Bağlı dik kenarlar birlikte taşınır. Ev duvarları korunur. Ev bağlantısında gerekirse dik bir kademe eklenir.</p><button id="verandaApply" class="sib" type="submit">Ölçüyü uygula</button><button id="verandaCancel" class="sib" type="button">İptal</button></form>';
 document.body.append(dialog);dialog.querySelectorAll('input,select').forEach(el=>el.style.cssText='display:block;box-sizing:border-box;width:100%;padding:9px;margin:8px 0 16px;background:#101b29;color:#d6e6ef');
 function preview(){try{const r=VerandaCore.resize(Studio.state(),target,+$('verandaNet').value,$('verandaFixed').value);$('verandaPreview').textContent=r.steps?r.steps+' ev bağlantısında dik kademe oluşacak. Ev duvarları taşınmaz.':'Bağlı veranda kenarları güncellenecek. Ev duvarları taşınmaz.';$('verandaApply').disabled=false;}catch(e){$('verandaPreview').textContent=e.message;$('verandaApply').disabled=true;}}
 function open(s){if(!s||s.tip!=='veranda')return;try{target=s.id;const d=Studio.state(),a=getNode(s.n1),b=getNode(s.n2),horizontal=Math.abs(a.y-b.y)<.001;const start=horizontal?(a.x<b.x?'Sol uç':'Sağ uç'):(a.y<b.y?'Üst uç':'Alt uç'),end=horizontal?(a.x<b.x?'Sağ uç':'Sol uç'):(a.y<b.y?'Alt uç':'Üst uç');$('verandaNet').value=+VerandaCore.measure(d,s.id).toFixed(4);$('verandaFixed').replaceChildren();for(const [value,label] of [['start',start+' sabit'],['end',end+' sabit'],['center','Merkez sabit']]){const o=document.createElement('option');o.value=value;o.textContent=label;$('verandaFixed').append(o);}const locked=id=>G.segs.some(q=>q.tip!=='veranda'&&(q.n1===id||q.n2===id));$('verandaFixed').value=locked(s.n2)&&!locked(s.n1)?'end':'start';preview();dialog.showModal();$('verandaNet').focus();$('verandaNet').select();}catch(e){Studio.toast(e.message,true);}}
 $('verandaNet').oninput=preview;$('verandaFixed').onchange=preview;$('verandaCancel').onclick=()=>dialog.close();
 function apply(id,value,fixed){let result;try{result=VerandaCore.resize(Studio.state(),id,value,fixed);}catch(e){Studio.toast(e.message,true);return false;}const ok=Studio.edit(()=>{G.nodes=result.state.n;G.segs=result.state.s;});if(ok)Studio.toast('Veranda net ölçüsü güncellendi.'+(result.steps?' Ev bağlantısında dik kademe eklendi.':''));return ok;}
 dialog.querySelector('form').onsubmit=e=>{e.preventDefault();if(apply(target,+$('verandaNet').value,$('verandaFixed').value))dialog.close();else preview();};
 const base=updateSidebar;window.updateSidebar=function(){base();const s=G.secili;if(!s||s.tip!=='veranda'||!['seg','dim'].includes(G.seciliTip))return;const box=$('sbSelIc');if(G.seciliTip==='seg')box.querySelector('.sr')?.remove();const row=document.createElement('div');row.className='sr';try{row.textContent='Net uzunluk: '+fmtCm(VerandaCore.measure(Studio.state(),s.id))+' cm';}catch{row.textContent='Eğik veranda sınırı';}const button=document.createElement('button');button.id='verandaEditMeasure';button.className='sib';button.textContent='Net ölçüyü düzenle';button.onclick=()=>open(s);box.prepend(row,button);};
 const resize=resizeSeg;window.resizeSeg=function(value){if(G.secili?.tip==='veranda')open(G.secili);else resize(value);};
 window.addEventListener('dblclick',e=>{if(e.target!==cv||G.tool!=='sec')return;const r=cv.getBoundingClientRect(),h=hitDim(e.clientX-r.left,e.clientY-r.top),s=h&&getSeg(h.segId);if(s?.tip==='veranda'){e.preventDefault();e.stopImmediatePropagation();open(s);}},true);
 window.VerandaEditor={open,apply};
})();
